/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`create_authorization`]
#[derive(Clone, Debug)]
pub struct CreateAuthorizationParams {
    pub authorization_request: models::AuthorizationRequest,
}

/// struct for passing parameters to the method [`delete_authorization`]
#[derive(Clone, Debug)]
pub struct DeleteAuthorizationParams {
    /// The key of the authorization to delete.
    pub authorization_key: String,
}

/// struct for passing parameters to the method [`get_authorization`]
#[derive(Clone, Debug)]
pub struct GetAuthorizationParams {
    /// The key of the authorization to get.
    pub authorization_key: String,
}

/// struct for passing parameters to the method [`search_authorizations`]
#[derive(Clone, Debug)]
pub struct SearchAuthorizationsParams {
    pub authorization_search_query: Option<models::AuthorizationSearchQuery>,
}

/// struct for passing parameters to the method [`update_authorization`]
#[derive(Clone, Debug)]
pub struct UpdateAuthorizationParams {
    /// The key of the authorization to delete.
    pub authorization_key: String,
    pub authorization_request: models::AuthorizationRequest,
}

/// struct for typed errors of method [`create_authorization`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateAuthorizationError {
    Status400(models::ProblemDetail),
    Status401(models::ProblemDetail),
    Status403(models::ProblemDetail),
    Status404(models::ProblemDetail),
    Status500(models::ProblemDetail),
    Status503(models::ProblemDetail),
    UnknownValue(serde_json::Value),
}

impl CreateAuthorizationError {
    /// Decode an error response body into the variant declared for `status`.
    ///
    /// The variants share payload types, so deserializing this untagged enum directly
    /// selects the first variant that fits, whatever the status.
    pub fn from_response(status: u16, content: &str) -> Option<Self> {
        let declared: Option<Self> = match status {
            400 => serde_json::from_str(content).ok().map(Self::Status400),
            401 => serde_json::from_str(content).ok().map(Self::Status401),
            403 => serde_json::from_str(content).ok().map(Self::Status403),
            404 => serde_json::from_str(content).ok().map(Self::Status404),
            500 => serde_json::from_str(content).ok().map(Self::Status500),
            503 => serde_json::from_str(content).ok().map(Self::Status503),
            _ => None,
        };
        declared.or_else(|| serde_json::from_str(content).ok().map(Self::UnknownValue))
    }
}

/// struct for typed errors of method [`delete_authorization`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAuthorizationError {
    Status401(models::ProblemDetail),
    Status404(models::ProblemDetail),
    Status500(models::ProblemDetail),
    Status503(models::ProblemDetail),
    UnknownValue(serde_json::Value),
}

impl DeleteAuthorizationError {
    /// Decode an error response body into the variant declared for `status`.
    ///
    /// The variants share payload types, so deserializing this untagged enum directly
    /// selects the first variant that fits, whatever the status.
    pub fn from_response(status: u16, content: &str) -> Option<Self> {
        let declared: Option<Self> = match status {
            401 => serde_json::from_str(content).ok().map(Self::Status401),
            404 => serde_json::from_str(content).ok().map(Self::Status404),
            500 => serde_json::from_str(content).ok().map(Self::Status500),
            503 => serde_json::from_str(content).ok().map(Self::Status503),
            _ => None,
        };
        declared.or_else(|| serde_json::from_str(content).ok().map(Self::UnknownValue))
    }
}

/// struct for typed errors of method [`get_authorization`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAuthorizationError {
    Status401(models::ProblemDetail),
    Status403(models::ProblemDetail),
    Status404(models::ProblemDetail),
    Status500(models::ProblemDetail),
    UnknownValue(serde_json::Value),
}

impl GetAuthorizationError {
    /// Decode an error response body into the variant declared for `status`.
    ///
    /// The variants share payload types, so deserializing this untagged enum directly
    /// selects the first variant that fits, whatever the status.
    pub fn from_response(status: u16, content: &str) -> Option<Self> {
        let declared: Option<Self> = match status {
            401 => serde_json::from_str(content).ok().map(Self::Status401),
            403 => serde_json::from_str(content).ok().map(Self::Status403),
            404 => serde_json::from_str(content).ok().map(Self::Status404),
            500 => serde_json::from_str(content).ok().map(Self::Status500),
            _ => None,
        };
        declared.or_else(|| serde_json::from_str(content).ok().map(Self::UnknownValue))
    }
}

/// struct for typed errors of method [`search_authorizations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchAuthorizationsError {
    Status400(models::ProblemDetail),
    Status401(models::ProblemDetail),
    Status403(models::ProblemDetail),
    Status500(models::ProblemDetail),
    UnknownValue(serde_json::Value),
}

impl SearchAuthorizationsError {
    /// Decode an error response body into the variant declared for `status`.
    ///
    /// The variants share payload types, so deserializing this untagged enum directly
    /// selects the first variant that fits, whatever the status.
    pub fn from_response(status: u16, content: &str) -> Option<Self> {
        let declared: Option<Self> = match status {
            400 => serde_json::from_str(content).ok().map(Self::Status400),
            401 => serde_json::from_str(content).ok().map(Self::Status401),
            403 => serde_json::from_str(content).ok().map(Self::Status403),
            500 => serde_json::from_str(content).ok().map(Self::Status500),
            _ => None,
        };
        declared.or_else(|| serde_json::from_str(content).ok().map(Self::UnknownValue))
    }
}

/// struct for typed errors of method [`update_authorization`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateAuthorizationError {
    Status401(models::ProblemDetail),
    Status404(models::ProblemDetail),
    Status500(models::ProblemDetail),
    Status503(models::ProblemDetail),
    UnknownValue(serde_json::Value),
}

impl UpdateAuthorizationError {
    /// Decode an error response body into the variant declared for `status`.
    ///
    /// The variants share payload types, so deserializing this untagged enum directly
    /// selects the first variant that fits, whatever the status.
    pub fn from_response(status: u16, content: &str) -> Option<Self> {
        let declared: Option<Self> = match status {
            401 => serde_json::from_str(content).ok().map(Self::Status401),
            404 => serde_json::from_str(content).ok().map(Self::Status404),
            500 => serde_json::from_str(content).ok().map(Self::Status500),
            503 => serde_json::from_str(content).ok().map(Self::Status503),
            _ => None,
        };
        declared.or_else(|| serde_json::from_str(content).ok().map(Self::UnknownValue))
    }
}

/// Create the authorization.
pub async fn create_authorization(
    configuration: &configuration::Configuration,
    params: CreateAuthorizationParams,
) -> Result<models::AuthorizationCreateResult, Error<CreateAuthorizationError>> {
    let uri_str = format!("{}/authorizations", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.authorization_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuthorizationCreateResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuthorizationCreateResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateAuthorizationError> =
            CreateAuthorizationError::from_response(status.as_u16(), &content);
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes the authorization with the given key.
pub async fn delete_authorization(
    configuration: &configuration::Configuration,
    params: DeleteAuthorizationParams,
) -> Result<(), Error<DeleteAuthorizationError>> {
    let uri_str = format!(
        "{}/authorizations/{authorizationKey}",
        configuration.base_path,
        authorizationKey = crate::apis::urlencode(params.authorization_key)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteAuthorizationError> =
            DeleteAuthorizationError::from_response(status.as_u16(), &content);
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get authorization by the given key.
pub async fn get_authorization(
    configuration: &configuration::Configuration,
    params: GetAuthorizationParams,
) -> Result<models::AuthorizationResult, Error<GetAuthorizationError>> {
    let uri_str = format!(
        "{}/authorizations/{authorizationKey}",
        configuration.base_path,
        authorizationKey = crate::apis::urlencode(params.authorization_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuthorizationResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuthorizationResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAuthorizationError> =
            GetAuthorizationError::from_response(status.as_u16(), &content);
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Search for authorizations based on given criteria.
pub async fn search_authorizations(
    configuration: &configuration::Configuration,
    params: SearchAuthorizationsParams,
) -> Result<models::AuthorizationSearchResult, Error<SearchAuthorizationsError>> {
    let uri_str = format!("{}/authorizations/search", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref body) = params.authorization_search_query {
        req_builder = req_builder.json(body);
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuthorizationSearchResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuthorizationSearchResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SearchAuthorizationsError> =
            SearchAuthorizationsError::from_response(status.as_u16(), &content);
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Update the authorization with the given key.
pub async fn update_authorization(
    configuration: &configuration::Configuration,
    params: UpdateAuthorizationParams,
) -> Result<(), Error<UpdateAuthorizationError>> {
    let uri_str = format!(
        "{}/authorizations/{authorizationKey}",
        configuration.base_path,
        authorizationKey = crate::apis::urlencode(params.authorization_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.authorization_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateAuthorizationError> =
            UpdateAuthorizationError::from_response(status.as_u16(), &content);
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
