/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`cancel_batch_operation`]
#[derive(Clone, Debug)]
pub struct CancelBatchOperationParams {
    /// The key (or operate legacy ID) of the batch operation.
    pub batch_operation_key: String,
}

/// struct for passing parameters to the method [`get_batch_operation`]
#[derive(Clone, Debug)]
pub struct GetBatchOperationParams {
    /// The key (or operate legacy ID) of the batch operation.
    pub batch_operation_key: String,
}

/// struct for passing parameters to the method [`resume_batch_operation`]
#[derive(Clone, Debug)]
pub struct ResumeBatchOperationParams {
    /// The key (or operate legacy ID) of the batch operation.
    pub batch_operation_key: String,
}

/// struct for passing parameters to the method [`search_batch_operation_items`]
#[derive(Clone, Debug)]
pub struct SearchBatchOperationItemsParams {
    pub batch_operation_item_search_query: Option<models::BatchOperationItemSearchQuery>,
}

/// struct for passing parameters to the method [`search_batch_operations`]
#[derive(Clone, Debug)]
pub struct SearchBatchOperationsParams {
    pub batch_operation_search_query: Option<models::BatchOperationSearchQuery>,
}

/// struct for passing parameters to the method [`suspend_batch_operation`]
#[derive(Clone, Debug)]
pub struct SuspendBatchOperationParams {
    /// The key (or operate legacy ID) of the batch operation.
    pub batch_operation_key: String,
}

/// struct for typed errors of method [`cancel_batch_operation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CancelBatchOperationError {
    Status400(),
    Status403(),
    Status404(models::ProblemDetail),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_batch_operation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBatchOperationError {
    Status400(models::ProblemDetail),
    Status404(models::ProblemDetail),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`resume_batch_operation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ResumeBatchOperationError {
    Status400(),
    Status403(),
    Status404(models::ProblemDetail),
    Status500(),
    Status503(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`search_batch_operation_items`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchBatchOperationItemsError {
    Status400(models::ProblemDetail),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`search_batch_operations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchBatchOperationsError {
    Status400(models::ProblemDetail),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`suspend_batch_operation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SuspendBatchOperationError {
    Status400(),
    Status403(),
    Status404(models::ProblemDetail),
    Status500(),
    Status503(),
    UnknownValue(serde_json::Value),
}

/// Cancels a running batch operation. This is done asynchronously, the progress can be tracked using the batch operation status endpoint (/batch-operations/{batchOperationKey}).
pub async fn cancel_batch_operation(
    configuration: &configuration::Configuration,
    params: CancelBatchOperationParams,
) -> Result<(), Error<CancelBatchOperationError>> {
    let uri_str = format!(
        "{}/batch-operations/{batchOperationKey}/cancellation",
        configuration.base_path,
        batchOperationKey = crate::apis::urlencode(params.batch_operation_key)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<CancelBatchOperationError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get batch operation by key.
pub async fn get_batch_operation(
    configuration: &configuration::Configuration,
    params: GetBatchOperationParams,
) -> Result<models::BatchOperationResponse, Error<GetBatchOperationError>> {
    let uri_str = format!(
        "{}/batch-operations/{batchOperationKey}",
        configuration.base_path,
        batchOperationKey = crate::apis::urlencode(params.batch_operation_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BatchOperationResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BatchOperationResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetBatchOperationError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Resumes a suspended batch operation. This is done asynchronously, the progress can be tracked using the batch operation status endpoint (/batch-operations/{batchOperationKey}).
pub async fn resume_batch_operation(
    configuration: &configuration::Configuration,
    params: ResumeBatchOperationParams,
) -> Result<(), Error<ResumeBatchOperationError>> {
    let uri_str = format!(
        "{}/batch-operations/{batchOperationKey}/resumption",
        configuration.base_path,
        batchOperationKey = crate::apis::urlencode(params.batch_operation_key)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ResumeBatchOperationError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Search for batch operation items based on given criteria.
pub async fn search_batch_operation_items(
    configuration: &configuration::Configuration,
    params: SearchBatchOperationItemsParams,
) -> Result<models::BatchOperationItemSearchQueryResult, Error<SearchBatchOperationItemsError>> {
    let uri_str = format!("{}/batch-operation-items/search", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.batch_operation_item_search_query);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BatchOperationItemSearchQueryResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BatchOperationItemSearchQueryResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SearchBatchOperationItemsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Search for batch operations based on given criteria.
pub async fn search_batch_operations(
    configuration: &configuration::Configuration,
    params: SearchBatchOperationsParams,
) -> Result<models::BatchOperationSearchQueryResult, Error<SearchBatchOperationsError>> {
    let uri_str = format!("{}/batch-operations/search", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.batch_operation_search_query);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BatchOperationSearchQueryResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BatchOperationSearchQueryResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SearchBatchOperationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Suspends a running batch operation. This is done asynchronously, the progress can be tracked using the batch operation status endpoint (/batch-operations/{batchOperationKey}).
pub async fn suspend_batch_operation(
    configuration: &configuration::Configuration,
    params: SuspendBatchOperationParams,
) -> Result<(), Error<SuspendBatchOperationError>> {
    let uri_str = format!(
        "{}/batch-operations/{batchOperationKey}/suspension",
        configuration.base_path,
        batchOperationKey = crate::apis::urlencode(params.batch_operation_key)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<SuspendBatchOperationError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
