/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`get_decision_requirements`]
#[derive(Clone, Debug)]
pub struct GetDecisionRequirementsParams {
    /// The assigned key of the decision requirements, which acts as a unique identifier for this decision requirements.
    pub decision_requirements_key: String,
}

/// struct for passing parameters to the method [`get_decision_requirements_xml`]
#[derive(Clone, Debug)]
pub struct GetDecisionRequirementsXmlParams {
    /// The assigned key of the decision requirements, which acts as a unique identifier for this decision.
    pub decision_requirements_key: String,
}

/// struct for passing parameters to the method [`search_decision_requirements`]
#[derive(Clone, Debug)]
pub struct SearchDecisionRequirementsParams {
    pub decision_requirements_search_query: Option<models::DecisionRequirementsSearchQuery>,
}

/// struct for typed errors of method [`get_decision_requirements`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetDecisionRequirementsError {
    Status400(),
    Status401(),
    Status403(),
    Status404(models::ProblemDetail),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_decision_requirements_xml`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetDecisionRequirementsXmlError {
    Status400(),
    Status401(),
    Status403(),
    Status404(models::ProblemDetail),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`search_decision_requirements`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchDecisionRequirementsError {
    Status400(),
    Status401(),
    Status403(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// Returns Decision Requirements as JSON.
pub async fn get_decision_requirements(
    configuration: &configuration::Configuration,
    params: GetDecisionRequirementsParams,
) -> Result<models::DecisionRequirementsResult, Error<GetDecisionRequirementsError>> {
    let uri_str = format!(
        "{}/decision-requirements/{decisionRequirementsKey}",
        configuration.base_path,
        decisionRequirementsKey = crate::apis::urlencode(params.decision_requirements_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DecisionRequirementsResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DecisionRequirementsResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetDecisionRequirementsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Returns decision requirements as XML.
pub async fn get_decision_requirements_xml(
    configuration: &configuration::Configuration,
    params: GetDecisionRequirementsXmlParams,
) -> Result<String, Error<GetDecisionRequirementsXmlError>> {
    let uri_str = format!(
        "{}/decision-requirements/{decisionRequirementsKey}/xml",
        configuration.base_path,
        decisionRequirementsKey = crate::apis::urlencode(params.decision_requirements_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetDecisionRequirementsXmlError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Search for decision requirements based on given criteria.
pub async fn search_decision_requirements(
    configuration: &configuration::Configuration,
    params: SearchDecisionRequirementsParams,
) -> Result<models::DecisionRequirementsSearchQueryResult, Error<SearchDecisionRequirementsError>> {
    let uri_str = format!("{}/decision-requirements/search", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.decision_requirements_search_query);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DecisionRequirementsSearchQueryResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DecisionRequirementsSearchQueryResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SearchDecisionRequirementsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
