/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`delete_decision_instance`]
#[derive(Clone, Debug)]
pub struct DeleteDecisionInstanceParams {
    /// The key of the decision evaluation to delete.
    pub decision_evaluation_key: String,
    pub delete_decision_instance_request: Option<models::DeleteDecisionInstanceRequest>,
}

/// struct for passing parameters to the method [`delete_decision_instances_batch_operation`]
#[derive(Clone, Debug)]
pub struct DeleteDecisionInstancesBatchOperationParams {
    pub decision_instance_deletion_batch_operation_request:
        models::DecisionInstanceDeletionBatchOperationRequest,
}

/// struct for passing parameters to the method [`get_decision_instance`]
#[derive(Clone, Debug)]
pub struct GetDecisionInstanceParams {
    /// The assigned key of the decision instance, which acts as a unique identifier for this decision instance.
    pub decision_evaluation_instance_key: String,
}

/// struct for passing parameters to the method [`search_decision_instances`]
#[derive(Clone, Debug)]
pub struct SearchDecisionInstancesParams {
    pub decision_instance_search_query: Option<models::DecisionInstanceSearchQuery>,
}

/// struct for typed errors of method [`delete_decision_instance`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteDecisionInstanceError {
    Status401(models::ProblemDetail),
    Status403(models::ProblemDetail),
    Status404(models::ProblemDetail),
    Status500(models::ProblemDetail),
    Status503(models::ProblemDetail),
    UnknownValue(serde_json::Value),
}

impl DeleteDecisionInstanceError {
    /// Decode an error response body into the variant declared for `status`.
    ///
    /// The variants share payload types, so deserializing this untagged enum directly
    /// selects the first variant that fits, whatever the status.
    pub fn from_response(status: u16, content: &str) -> Option<Self> {
        let declared: Option<Self> = match status {
            401 => serde_json::from_str(content).ok().map(Self::Status401),
            403 => serde_json::from_str(content).ok().map(Self::Status403),
            404 => serde_json::from_str(content).ok().map(Self::Status404),
            500 => serde_json::from_str(content).ok().map(Self::Status500),
            503 => serde_json::from_str(content).ok().map(Self::Status503),
            _ => None,
        };
        declared.or_else(|| serde_json::from_str(content).ok().map(Self::UnknownValue))
    }
}

/// struct for typed errors of method [`delete_decision_instances_batch_operation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteDecisionInstancesBatchOperationError {
    Status400(models::ProblemDetail),
    Status401(models::ProblemDetail),
    Status403(models::ProblemDetail),
    Status500(models::ProblemDetail),
    UnknownValue(serde_json::Value),
}

impl DeleteDecisionInstancesBatchOperationError {
    /// Decode an error response body into the variant declared for `status`.
    ///
    /// The variants share payload types, so deserializing this untagged enum directly
    /// selects the first variant that fits, whatever the status.
    pub fn from_response(status: u16, content: &str) -> Option<Self> {
        let declared: Option<Self> = match status {
            400 => serde_json::from_str(content).ok().map(Self::Status400),
            401 => serde_json::from_str(content).ok().map(Self::Status401),
            403 => serde_json::from_str(content).ok().map(Self::Status403),
            500 => serde_json::from_str(content).ok().map(Self::Status500),
            _ => None,
        };
        declared.or_else(|| serde_json::from_str(content).ok().map(Self::UnknownValue))
    }
}

/// struct for typed errors of method [`get_decision_instance`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetDecisionInstanceError {
    Status400(models::ProblemDetail),
    Status401(models::ProblemDetail),
    Status403(models::ProblemDetail),
    Status404(models::ProblemDetail),
    Status500(models::ProblemDetail),
    UnknownValue(serde_json::Value),
}

impl GetDecisionInstanceError {
    /// Decode an error response body into the variant declared for `status`.
    ///
    /// The variants share payload types, so deserializing this untagged enum directly
    /// selects the first variant that fits, whatever the status.
    pub fn from_response(status: u16, content: &str) -> Option<Self> {
        let declared: Option<Self> = match status {
            400 => serde_json::from_str(content).ok().map(Self::Status400),
            401 => serde_json::from_str(content).ok().map(Self::Status401),
            403 => serde_json::from_str(content).ok().map(Self::Status403),
            404 => serde_json::from_str(content).ok().map(Self::Status404),
            500 => serde_json::from_str(content).ok().map(Self::Status500),
            _ => None,
        };
        declared.or_else(|| serde_json::from_str(content).ok().map(Self::UnknownValue))
    }
}

/// struct for typed errors of method [`search_decision_instances`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchDecisionInstancesError {
    Status400(models::ProblemDetail),
    Status401(models::ProblemDetail),
    Status403(models::ProblemDetail),
    Status500(models::ProblemDetail),
    UnknownValue(serde_json::Value),
}

impl SearchDecisionInstancesError {
    /// Decode an error response body into the variant declared for `status`.
    ///
    /// The variants share payload types, so deserializing this untagged enum directly
    /// selects the first variant that fits, whatever the status.
    pub fn from_response(status: u16, content: &str) -> Option<Self> {
        let declared: Option<Self> = match status {
            400 => serde_json::from_str(content).ok().map(Self::Status400),
            401 => serde_json::from_str(content).ok().map(Self::Status401),
            403 => serde_json::from_str(content).ok().map(Self::Status403),
            500 => serde_json::from_str(content).ok().map(Self::Status500),
            _ => None,
        };
        declared.or_else(|| serde_json::from_str(content).ok().map(Self::UnknownValue))
    }
}

/// Delete all associated decision evaluations based on provided key.
pub async fn delete_decision_instance(
    configuration: &configuration::Configuration,
    params: DeleteDecisionInstanceParams,
) -> Result<(), Error<DeleteDecisionInstanceError>> {
    let uri_str = format!(
        "{}/decision-instances/{decisionEvaluationKey}/deletion",
        configuration.base_path,
        decisionEvaluationKey = crate::apis::urlencode(params.decision_evaluation_key)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref body) = params.delete_decision_instance_request {
        req_builder = req_builder.json(body);
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteDecisionInstanceError> =
            DeleteDecisionInstanceError::from_response(status.as_u16(), &content);
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Delete multiple decision instances. This will delete the historic data from secondary storage. This is done asynchronously, the progress can be tracked using the batchOperationKey from the response and the batch operation status endpoint (/batch-operations/{batchOperationKey}).
pub async fn delete_decision_instances_batch_operation(
    configuration: &configuration::Configuration,
    params: DeleteDecisionInstancesBatchOperationParams,
) -> Result<models::BatchOperationCreatedResult, Error<DeleteDecisionInstancesBatchOperationError>>
{
    let uri_str = format!("{}/decision-instances/deletion", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.decision_instance_deletion_batch_operation_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BatchOperationCreatedResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BatchOperationCreatedResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteDecisionInstancesBatchOperationError> =
            DeleteDecisionInstancesBatchOperationError::from_response(status.as_u16(), &content);
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Returns a decision instance.
pub async fn get_decision_instance(
    configuration: &configuration::Configuration,
    params: GetDecisionInstanceParams,
) -> Result<models::DecisionInstanceGetQueryResult, Error<GetDecisionInstanceError>> {
    let uri_str = format!(
        "{}/decision-instances/{decisionEvaluationInstanceKey}",
        configuration.base_path,
        decisionEvaluationInstanceKey =
            crate::apis::urlencode(params.decision_evaluation_instance_key)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DecisionInstanceGetQueryResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DecisionInstanceGetQueryResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetDecisionInstanceError> =
            GetDecisionInstanceError::from_response(status.as_u16(), &content);
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Search for decision instances based on given criteria.
pub async fn search_decision_instances(
    configuration: &configuration::Configuration,
    params: SearchDecisionInstancesParams,
) -> Result<models::DecisionInstanceSearchQueryResult, Error<SearchDecisionInstancesError>> {
    let uri_str = format!("{}/decision-instances/search", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref body) = params.decision_instance_search_query {
        req_builder = req_builder.json(body);
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DecisionInstanceSearchQueryResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DecisionInstanceSearchQueryResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SearchDecisionInstancesError> =
            SearchDecisionInstancesError::from_response(status.as_u16(), &content);
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
