/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`create_global_task_listener`]
#[derive(Clone, Debug)]
pub struct CreateGlobalTaskListenerParams {
    pub create_global_task_listener_request: models::CreateGlobalTaskListenerRequest,
}

/// struct for passing parameters to the method [`delete_global_task_listener`]
#[derive(Clone, Debug)]
pub struct DeleteGlobalTaskListenerParams {
    /// The id of the global user task listener to delete.
    pub id: String,
}

/// struct for passing parameters to the method [`get_global_task_listener`]
#[derive(Clone, Debug)]
pub struct GetGlobalTaskListenerParams {
    /// The id of the global user task listener.
    pub id: String,
}

/// struct for passing parameters to the method [`search_global_task_listeners`]
#[derive(Clone, Debug)]
pub struct SearchGlobalTaskListenersParams {
    pub global_task_listener_search_query_request:
        Option<models::GlobalTaskListenerSearchQueryRequest>,
}

/// struct for passing parameters to the method [`update_global_task_listener`]
#[derive(Clone, Debug)]
pub struct UpdateGlobalTaskListenerParams {
    /// The id of the global user task listener to update.
    pub id: String,
    pub update_global_task_listener_request: models::UpdateGlobalTaskListenerRequest,
}

/// struct for typed errors of method [`create_global_task_listener`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateGlobalTaskListenerError {
    Status400(),
    Status401(),
    Status403(),
    Status409(models::ProblemDetail),
    Status500(),
    Status503(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_global_task_listener`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteGlobalTaskListenerError {
    Status400(),
    Status401(),
    Status403(),
    Status404(models::ProblemDetail),
    Status500(),
    Status503(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_global_task_listener`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetGlobalTaskListenerError {
    Status401(),
    Status403(),
    Status404(models::ProblemDetail),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`search_global_task_listeners`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchGlobalTaskListenersError {
    Status400(),
    Status401(),
    Status403(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_global_task_listener`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateGlobalTaskListenerError {
    Status400(),
    Status401(),
    Status403(),
    Status404(models::ProblemDetail),
    Status500(),
    Status503(),
    UnknownValue(serde_json::Value),
}

/// Create a new global user task listener.
pub async fn create_global_task_listener(
    configuration: &configuration::Configuration,
    params: CreateGlobalTaskListenerParams,
) -> Result<models::GlobalTaskListenerResult, Error<CreateGlobalTaskListenerError>> {
    let uri_str = format!("{}/global-task-listeners", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.create_global_task_listener_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GlobalTaskListenerResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GlobalTaskListenerResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateGlobalTaskListenerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes a global user task listener.
pub async fn delete_global_task_listener(
    configuration: &configuration::Configuration,
    params: DeleteGlobalTaskListenerParams,
) -> Result<(), Error<DeleteGlobalTaskListenerError>> {
    let uri_str = format!(
        "{}/global-task-listeners/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(params.id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteGlobalTaskListenerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get a global user task listener by its id.
pub async fn get_global_task_listener(
    configuration: &configuration::Configuration,
    params: GetGlobalTaskListenerParams,
) -> Result<models::GlobalTaskListenerResult, Error<GetGlobalTaskListenerError>> {
    let uri_str = format!(
        "{}/global-task-listeners/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(params.id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GlobalTaskListenerResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GlobalTaskListenerResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetGlobalTaskListenerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Search for global user task listeners based on given criteria.
pub async fn search_global_task_listeners(
    configuration: &configuration::Configuration,
    params: SearchGlobalTaskListenersParams,
) -> Result<models::GlobalTaskListenerSearchQueryResult, Error<SearchGlobalTaskListenersError>> {
    let uri_str = format!("{}/global-task-listeners/search", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.global_task_listener_search_query_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GlobalTaskListenerSearchQueryResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GlobalTaskListenerSearchQueryResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SearchGlobalTaskListenersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Updates a global user task listener.
pub async fn update_global_task_listener(
    configuration: &configuration::Configuration,
    params: UpdateGlobalTaskListenerParams,
) -> Result<models::GlobalTaskListenerResult, Error<UpdateGlobalTaskListenerError>> {
    let uri_str = format!(
        "{}/global-task-listeners/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(params.id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.update_global_task_listener_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GlobalTaskListenerResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GlobalTaskListenerResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateGlobalTaskListenerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
