/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`get_license`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLicenseError {
    Status500(models::ProblemDetail),
    UnknownValue(serde_json::Value),
}

impl GetLicenseError {
    /// Decode an error response body into the variant declared for `status`.
    ///
    /// The variants share payload types, so deserializing this untagged enum directly
    /// selects the first variant that fits, whatever the status.
    pub fn from_response(status: u16, content: &str) -> Option<Self> {
        let declared: Option<Self> = match status {
            500 => serde_json::from_str(content).ok().map(Self::Status500),
            _ => None,
        };
        declared.or_else(|| serde_json::from_str(content).ok().map(Self::UnknownValue))
    }
}

/// Obtains the status of the current Camunda license.
pub async fn get_license(
    configuration: &configuration::Configuration,
) -> Result<models::LicenseResponse, Error<GetLicenseError>> {
    let uri_str = format!("{}/license", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LicenseResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LicenseResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLicenseError> =
            GetLicenseError::from_response(status.as_u16(), &content);
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
