/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdvancedEntityTypeFilter : Advanced AuditLogEntityTypeEnum filter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdvancedEntityTypeFilter {
    /// Checks for equality with the provided value.
    #[serde(rename = "$eq", skip_serializing_if = "Option::is_none")]
    pub dollar_eq: Option<models::AuditLogEntityTypeEnum>,
    /// Checks for inequality with the provided value.
    #[serde(rename = "$neq", skip_serializing_if = "Option::is_none")]
    pub dollar_neq: Option<models::AuditLogEntityTypeEnum>,
    /// Checks if the current property exists.
    #[serde(rename = "$exists", skip_serializing_if = "Option::is_none")]
    pub dollar_exists: Option<bool>,
    /// Checks if the property matches any of the provided values.
    #[serde(rename = "$in", skip_serializing_if = "Option::is_none")]
    pub dollar_in: Option<Vec<models::AuditLogEntityTypeEnum>>,
    /// Checks if the property matches the provided like value.  Supported wildcard characters are:  * `*`: matches zero, one, or multiple characters. * `?`: matches one, single character.  Wildcard characters can be escaped with backslash, for instance: `\\*`.
    #[serde(rename = "$like", skip_serializing_if = "Option::is_none")]
    pub dollar_like: Option<String>,
}

impl AdvancedEntityTypeFilter {
    /// Advanced AuditLogEntityTypeEnum filter.
    pub fn new() -> AdvancedEntityTypeFilter {
        AdvancedEntityTypeFilter {
            dollar_eq: None,
            dollar_neq: None,
            dollar_exists: None,
            dollar_in: None,
            dollar_like: None,
        }
    }
}
