/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentDefinitionFilter : Agent definition search filter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentDefinitionFilter {
    /// The unique key of the agent definition.
    #[serde(rename = "agentDefinitionKey", skip_serializing_if = "Option::is_none")]
    pub agent_definition_key: Option<Box<models::AgentDefinitionKeyFilterProperty>>,
    /// The kind of agent this agent definition describes.
    #[serde(rename = "agentType", skip_serializing_if = "Option::is_none")]
    pub agent_type: Option<Box<models::AgentDefinitionTypeFilterProperty>>,
    /// The human-readable name of the process element that owns the agent definition.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Box<models::StringFilterProperty>>,
    /// The BPMN element ID of the process element that owns the agent definition.
    #[serde(rename = "elementId", skip_serializing_if = "Option::is_none")]
    pub element_id: Option<Box<models::ElementIdFilterProperty>>,
    /// The BPMN process ID of the process definition that owns the agent definition.
    #[serde(
        rename = "processDefinitionId",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_id: Option<Box<models::ProcessDefinitionIdFilterProperty>>,
    /// The key of the process definition that owns the agent definition.
    #[serde(
        rename = "processDefinitionKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_key: Option<Box<models::ProcessDefinitionKeyFilterProperty>>,
    /// The version of the process definition that owns the agent definition.
    #[serde(
        rename = "processDefinitionVersion",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_version: Option<Box<models::IntegerFilterProperty>>,
    /// The version tag of the process definition that owns the agent definition.
    #[serde(
        rename = "processDefinitionVersionTag",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_version_tag: Option<Box<models::StringFilterProperty>>,
    /// The tenant ID of the agent definition.
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Box<models::StringFilterProperty>>,
}

impl AgentDefinitionFilter {
    /// Agent definition search filter.
    pub fn new() -> AgentDefinitionFilter {
        AgentDefinitionFilter {
            agent_definition_key: None,
            agent_type: None,
            name: None,
            element_id: None,
            process_definition_id: None,
            process_definition_key: None,
            process_definition_version: None,
            process_definition_version_tag: None,
            tenant_id: None,
        }
    }
}
