/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentTool : A tool available to the agent.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentTool {
    /// The tool name as visible to the LLM.
    #[serde(rename = "name")]
    pub name: String,
    /// A human-readable description of the tool.
    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<String>,
    /// The BPMN element ID of the tool element within the ad-hoc sub-process.
    #[serde(rename = "elementId", deserialize_with = "Option::deserialize")]
    pub element_id: Option<String>,
}

impl AgentTool {
    /// A tool available to the agent.
    pub fn new(name: String, description: Option<String>, element_id: Option<String>) -> AgentTool {
        AgentTool {
            name,
            description,
            element_id,
        }
    }
}
