/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentInstanceMessageContentTypeEnum : The content type discriminator for a history item content block.
/// The content type discriminator for a history item content block.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AgentInstanceMessageContentTypeEnum {
    #[serde(rename = "TEXT")]
    Text,
    #[serde(rename = "DOCUMENT")]
    Document,
    #[serde(rename = "OBJECT")]
    Object,
}

impl std::fmt::Display for AgentInstanceMessageContentTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Text => write!(f, "TEXT"),
            Self::Document => write!(f, "DOCUMENT"),
            Self::Object => write!(f, "OBJECT"),
        }
    }
}

impl Default for AgentInstanceMessageContentTypeEnum {
    fn default() -> AgentInstanceMessageContentTypeEnum {
        Self::Text
    }
}
