/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentInstanceDefinition : The static definition of an agent instance, set once at creation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentInstanceDefinition {
    /// The LLM model identifier (for example, gpt-4o).
    #[serde(rename = "model")]
    pub model: String,
    /// The LLM provider (for example, openai or anthropic).
    #[serde(rename = "provider")]
    pub provider: String,
    /// The system prompt configured for this agent instance.
    #[serde(rename = "systemPrompt")]
    pub system_prompt: String,
}

impl AgentInstanceDefinition {
    /// The static definition of an agent instance, set once at creation.
    pub fn new(model: String, provider: String, system_prompt: String) -> AgentInstanceDefinition {
        AgentInstanceDefinition {
            model,
            provider,
            system_prompt,
        }
    }
}
