/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentInstanceHistoryItem : A single history item to append to the agent instance's conversation history, submitted as part of the batch on an agent instance update request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentInstanceHistoryItem {
    /// Caller-assigned identifier used to detect and dedupe retries of the same item. For example, when a retried job activation resubmits history items it already sent in an earlier attempt, those items are not rejected; they are flagged via isDuplicate in the response instead. Must be non-blank.
    #[serde(rename = "historyItemId")]
    pub history_item_id: models::HistoryItemId,
    /// The loop iteration this item belongs to.
    #[serde(rename = "loopIteration")]
    pub loop_iteration: i32,
    /// The role of this history item in the conversation.
    #[serde(rename = "role")]
    pub role: models::AgentInstanceHistoryRoleEnum,
    /// The content blocks of this history item.
    #[serde(rename = "content")]
    pub content: Vec<models::AgentInstanceMessageContent>,
    /// Tool calls associated with this history item. For ASSISTANT items: tool calls dispatched by this LLM response. For TOOL_RESULT items: single-entry array referencing the originating tool call. Omit for USER items.
    #[serde(
        rename = "toolCalls",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tool_calls: Option<Option<Vec<models::AgentInstanceToolCall>>>,
    /// Per-call token and latency metrics. Present on ASSISTANT items only.
    #[serde(
        rename = "metrics",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub metrics: Option<Option<Box<models::AgentInstanceHistoryItemMetricsRequest>>>,
    /// The agent-side timestamp of when this message was produced.
    #[serde(rename = "producedAt")]
    pub produced_at: chrono::DateTime<chrono::FixedOffset>,
    /// The complete list of tools available to the agent as of this entry. CONFIGURATION items only; omit for other roles. Omit to leave the tool list unchanged; send an empty array to clear it.
    #[serde(
        rename = "tools",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tools: Option<Option<Vec<models::AgentTool>>>,
    /// The LLM model identifier as of this entry. CONFIGURATION items only; omit for other roles.
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// The LLM provider as of this entry. CONFIGURATION items only; omit for other roles.
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    /// The operational limits as of this entry. CONFIGURATION items only; omit for other roles.
    #[serde(rename = "limits", skip_serializing_if = "Option::is_none")]
    pub limits: Option<Box<models::AgentInstanceLimits>>,
    /// The system prompt, as content blocks, as of this entry. CONFIGURATION items only; omit for other roles. Omit to leave the system prompt unchanged; when present, must be non-empty.
    #[serde(
        rename = "systemPrompt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub system_prompt: Option<Option<Vec<models::AgentInstanceMessageContent>>>,
}

impl AgentInstanceHistoryItem {
    /// A single history item to append to the agent instance's conversation history, submitted as part of the batch on an agent instance update request.
    pub fn new(
        history_item_id: models::HistoryItemId,
        loop_iteration: i32,
        role: models::AgentInstanceHistoryRoleEnum,
        content: Vec<models::AgentInstanceMessageContent>,
        produced_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> AgentInstanceHistoryItem {
        AgentInstanceHistoryItem {
            history_item_id,
            loop_iteration,
            role,
            content,
            tool_calls: None,
            metrics: None,
            produced_at,
            tools: None,
            model: None,
            provider: None,
            limits: None,
            system_prompt: None,
        }
    }
}
