/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentInstanceUpdateRequest : Request to update the mutable state of an agent instance.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentInstanceUpdateRequest {
    /// The key of the currently-active element instance for this agent instance. Used for ownership/equality validation against the stored agent instance and, when the supplied key differs from the previous association (re-entry of an ad-hoc sub-process or AI Agent task), appended to elementInstanceKeys with the reverse link updated on the supplied element instance.
    #[serde(rename = "elementInstanceKey")]
    pub element_instance_key: Box<models::ElementInstanceKey>,
    /// The new status of the agent instance.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::AgentInstanceUpdateStatusEnum>,
    /// Metric increments to apply to the aggregate counters.
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Box<models::AgentInstanceMetricsDelta>>,
    /// The complete list of tools available to the agent, replacing any previously stored tools. When provided, the engine replaces the existing tool list with this value.
    #[serde(
        rename = "tools",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tools: Option<Option<Vec<models::AgentTool>>>,
}

impl AgentInstanceUpdateRequest {
    /// Request to update the mutable state of an agent instance.
    pub fn new(element_instance_key: models::ElementInstanceKey) -> AgentInstanceUpdateRequest {
        AgentInstanceUpdateRequest {
            element_instance_key: Box::new(element_instance_key),
            status: None,
            metrics: None,
            tools: None,
        }
    }
}
