/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentInstanceToolCall : A tool call associated with a history item. Used in both ASSISTANT and TOOL_RESULT items. ASSISTANT items carry arguments; TOOL_RESULT items carry arguments as null.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentInstanceToolCall {
    /// The LLM-assigned tool call ID. Correlates ASSISTANT items to their matching TOOL_RESULT items.
    #[serde(rename = "toolCallId")]
    pub tool_call_id: String,
    /// The LLM-visible tool name.
    #[serde(rename = "toolName")]
    pub tool_name: String,
    /// The BPMN element ID handling this tool.
    #[serde(rename = "elementId", deserialize_with = "Option::deserialize")]
    pub element_id: Option<String>,
    /// The tool call arguments as provided by the LLM. Null on TOOL_RESULT items.
    #[serde(rename = "arguments", deserialize_with = "Option::deserialize")]
    pub arguments: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl AgentInstanceToolCall {
    /// A tool call associated with a history item. Used in both ASSISTANT and TOOL_RESULT items. ASSISTANT items carry arguments; TOOL_RESULT items carry arguments as null.
    pub fn new(
        tool_call_id: String,
        tool_name: String,
        element_id: Option<String>,
        arguments: Option<std::collections::HashMap<String, serde_json::Value>>,
    ) -> AgentInstanceToolCall {
        AgentInstanceToolCall {
            tool_call_id,
            tool_name,
            element_id,
            arguments,
        }
    }
}
