/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentInstanceHistoryFilter : Agent instance history item search filter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentInstanceHistoryFilter {
    /// The unique key of the history item.
    #[serde(rename = "historyItemKey", skip_serializing_if = "Option::is_none")]
    pub history_item_key: Option<Box<models::AgentHistoryItemKeyFilterProperty>>,
    /// The role of the history item.
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Box<models::AgentInstanceHistoryRoleFilterProperty>>,
    /// The key of the element instance under which the history item was produced.
    #[serde(rename = "elementInstanceKey", skip_serializing_if = "Option::is_none")]
    pub element_instance_key: Option<Box<models::ElementInstanceKeyFilterProperty>>,
    /// The key of the job activation that produced the history item.
    #[serde(rename = "jobKey", skip_serializing_if = "Option::is_none")]
    pub job_key: Option<Box<models::JobKeyFilterProperty>>,
    /// Filter by loopIteration number. A loopIteration is one pass through the agent feedback loop (one LLM call, its tool dispatches, and their results).
    #[serde(rename = "loopIteration", skip_serializing_if = "Option::is_none")]
    pub loop_iteration: Option<Box<models::IntegerFilterProperty>>,
    /// The commit status of the history item. Defaults to COMMITTED only. Include PENDING or DISCARDED explicitly to debug in-flight or failed activations.
    #[serde(rename = "commitStatus", skip_serializing_if = "Option::is_none")]
    pub commit_status: Option<Box<models::AgentInstanceHistoryCommitStatusFilterProperty>>,
    /// The timestamp when the history item was produced.
    #[serde(rename = "producedAt", skip_serializing_if = "Option::is_none")]
    pub produced_at: Option<Box<models::DateTimeFilterProperty>>,
}

impl AgentInstanceHistoryFilter {
    /// Agent instance history item search filter.
    pub fn new() -> AgentInstanceHistoryFilter {
        AgentInstanceHistoryFilter {
            history_item_key: None,
            role: None,
            element_instance_key: None,
            job_key: None,
            loop_iteration: None,
            commit_status: None,
            produced_at: None,
        }
    }
}
