/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentInstanceCreatedHistoryItem : The outcome of appending a single history item from an update request's history batch.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentInstanceCreatedHistoryItem {
    /// The historyItemId of the corresponding item in the request, echoed back so callers can correlate response entries with request items by id.
    #[serde(rename = "historyItemId")]
    pub history_item_id: models::HistoryItemId,
    /// The system-generated key for the history item. When isDuplicate is true, this is the key of the original entry, not a new one.
    #[serde(rename = "historyItemKey")]
    pub history_item_key: Box<models::AgentHistoryItemKey>,
    /// True if this item had already been recorded and no new AGENT_HISTORY event was created for it; false if a new event was created.
    #[serde(rename = "isDuplicate")]
    pub is_duplicate: bool,
}

impl AgentInstanceCreatedHistoryItem {
    /// The outcome of appending a single history item from an update request's history batch.
    pub fn new(
        history_item_id: models::HistoryItemId,
        history_item_key: models::AgentHistoryItemKey,
        is_duplicate: bool,
    ) -> AgentInstanceCreatedHistoryItem {
        AgentInstanceCreatedHistoryItem {
            history_item_id,
            history_item_key: Box::new(history_item_key),
            is_duplicate,
        }
    }
}
