/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuditLogFilter : Audit log filter request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditLogFilter {
    /// The audit log key search filter.
    #[serde(rename = "auditLogKey", skip_serializing_if = "Option::is_none")]
    pub audit_log_key: Option<Box<models::AuditLogKeyFilterProperty>>,
    /// The process definition key search filter.
    #[serde(
        rename = "processDefinitionKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_key: Option<Box<models::ProcessDefinitionKeyFilterProperty>>,
    /// The process instance key search filter.
    #[serde(rename = "processInstanceKey", skip_serializing_if = "Option::is_none")]
    pub process_instance_key: Option<Box<models::ProcessInstanceKeyFilterProperty>>,
    /// The element instance key search filter.
    #[serde(rename = "elementInstanceKey", skip_serializing_if = "Option::is_none")]
    pub element_instance_key: Option<Box<models::ElementInstanceKeyFilterProperty>>,
    /// The operation type search filter.
    #[serde(rename = "operationType", skip_serializing_if = "Option::is_none")]
    pub operation_type: Option<Box<models::OperationTypeFilterProperty>>,
    /// The result search filter.
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::AuditLogResultFilterProperty>>,
    /// The timestamp search filter.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Box<models::DateTimeFilterProperty>>,
    /// The actor ID search filter.
    #[serde(rename = "actorId", skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<Box<models::StringFilterProperty>>,
    /// The actor type search filter.
    #[serde(rename = "actorType", skip_serializing_if = "Option::is_none")]
    pub actor_type: Option<Box<models::AuditLogActorTypeFilterProperty>>,
    /// The agent element ID search filter.
    #[serde(rename = "agentElementId", skip_serializing_if = "Option::is_none")]
    pub agent_element_id: Option<Box<models::StringFilterProperty>>,
    /// The entity key search filter.
    #[serde(rename = "entityKey", skip_serializing_if = "Option::is_none")]
    pub entity_key: Option<Box<models::AuditLogEntityKeyFilterProperty>>,
    /// The entity type search filter.
    #[serde(rename = "entityType", skip_serializing_if = "Option::is_none")]
    pub entity_type: Option<Box<models::EntityTypeFilterProperty>>,
    /// The tenant ID search filter.
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Box<models::StringFilterProperty>>,
    /// The category search filter.
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Box<models::CategoryFilterProperty>>,
    /// The deployment key search filter.
    #[serde(rename = "deploymentKey", skip_serializing_if = "Option::is_none")]
    pub deployment_key: Option<Box<models::DeploymentKeyFilterProperty>>,
    /// The form key search filter.
    #[serde(rename = "formKey", skip_serializing_if = "Option::is_none")]
    pub form_key: Option<Box<models::FormKeyFilterProperty>>,
    /// The resource key search filter.
    #[serde(rename = "resourceKey", skip_serializing_if = "Option::is_none")]
    pub resource_key: Option<Box<models::ResourceKeyFilterProperty>>,
    /// The batch operation type search filter.
    #[serde(rename = "batchOperationType", skip_serializing_if = "Option::is_none")]
    pub batch_operation_type: Option<Box<models::BatchOperationTypeFilterProperty>>,
    /// The process definition ID search filter.
    #[serde(
        rename = "processDefinitionId",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_id: Option<Box<models::StringFilterProperty>>,
    /// The job key search filter.
    #[serde(rename = "jobKey", skip_serializing_if = "Option::is_none")]
    pub job_key: Option<Box<models::JobKeyFilterProperty>>,
    /// The user task key search filter.
    #[serde(rename = "userTaskKey", skip_serializing_if = "Option::is_none")]
    pub user_task_key: Option<Box<models::BasicStringFilterProperty>>,
    /// The decision requirements ID search filter.
    #[serde(
        rename = "decisionRequirementsId",
        skip_serializing_if = "Option::is_none"
    )]
    pub decision_requirements_id: Option<Box<models::StringFilterProperty>>,
    /// The decision requirements key search filter.
    #[serde(
        rename = "decisionRequirementsKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub decision_requirements_key: Option<Box<models::DecisionRequirementsKeyFilterProperty>>,
    /// The decision definition ID search filter.
    #[serde(
        rename = "decisionDefinitionId",
        skip_serializing_if = "Option::is_none"
    )]
    pub decision_definition_id: Option<Box<models::StringFilterProperty>>,
    /// The decision definition key search filter.
    #[serde(
        rename = "decisionDefinitionKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub decision_definition_key: Option<Box<models::DecisionDefinitionKeyFilterProperty>>,
    /// The decision evaluation key search filter.
    #[serde(
        rename = "decisionEvaluationKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub decision_evaluation_key: Option<Box<models::DecisionEvaluationKeyFilterProperty>>,
    /// The related entity key search filter.
    #[serde(rename = "relatedEntityKey", skip_serializing_if = "Option::is_none")]
    pub related_entity_key: Option<Box<models::AuditLogEntityKeyFilterProperty>>,
    /// The related entity type search filter.
    #[serde(rename = "relatedEntityType", skip_serializing_if = "Option::is_none")]
    pub related_entity_type: Option<Box<models::EntityTypeFilterProperty>>,
    /// The entity description filter.
    #[serde(rename = "entityDescription", skip_serializing_if = "Option::is_none")]
    pub entity_description: Option<Box<models::StringFilterProperty>>,
    /// The inbound channel type search filter (e.g. MCP).
    #[serde(rename = "inboundChannelType", skip_serializing_if = "Option::is_none")]
    pub inbound_channel_type: Option<Box<models::StringFilterProperty>>,
    /// The inbound channel tool name search filter.
    #[serde(
        rename = "inboundChannelToolName",
        skip_serializing_if = "Option::is_none"
    )]
    pub inbound_channel_tool_name: Option<Box<models::StringFilterProperty>>,
}

impl AuditLogFilter {
    /// Audit log filter request
    pub fn new() -> AuditLogFilter {
        AuditLogFilter {
            audit_log_key: None,
            process_definition_key: None,
            process_instance_key: None,
            element_instance_key: None,
            operation_type: None,
            result: None,
            timestamp: None,
            actor_id: None,
            actor_type: None,
            agent_element_id: None,
            entity_key: None,
            entity_type: None,
            tenant_id: None,
            category: None,
            deployment_key: None,
            form_key: None,
            resource_key: None,
            batch_operation_type: None,
            process_definition_id: None,
            job_key: None,
            user_task_key: None,
            decision_requirements_id: None,
            decision_requirements_key: None,
            decision_definition_id: None,
            decision_definition_key: None,
            decision_evaluation_key: None,
            related_entity_key: None,
            related_entity_type: None,
            entity_description: None,
            inbound_channel_type: None,
            inbound_channel_tool_name: None,
        }
    }
}
