/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuditLogOperationTypeEnum : The type of operation performed.
/// The type of operation performed.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuditLogOperationTypeEnum {
    #[serde(rename = "ASSIGN")]
    Assign,
    #[serde(rename = "CANCEL")]
    Cancel,
    #[serde(rename = "COMPLETE")]
    Complete,
    #[serde(rename = "CREATE")]
    Create,
    #[serde(rename = "DELETE")]
    Delete,
    #[serde(rename = "EVALUATE")]
    Evaluate,
    #[serde(rename = "MIGRATE")]
    Migrate,
    #[serde(rename = "MODIFY")]
    Modify,
    #[serde(rename = "RESOLVE")]
    Resolve,
    #[serde(rename = "RESUME")]
    Resume,
    #[serde(rename = "SUSPEND")]
    Suspend,
    #[serde(rename = "UNASSIGN")]
    Unassign,
    #[serde(rename = "UNKNOWN")]
    Unknown,
    #[serde(rename = "UPDATE")]
    Update,
}

impl std::fmt::Display for AuditLogOperationTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Assign => write!(f, "ASSIGN"),
            Self::Cancel => write!(f, "CANCEL"),
            Self::Complete => write!(f, "COMPLETE"),
            Self::Create => write!(f, "CREATE"),
            Self::Delete => write!(f, "DELETE"),
            Self::Evaluate => write!(f, "EVALUATE"),
            Self::Migrate => write!(f, "MIGRATE"),
            Self::Modify => write!(f, "MODIFY"),
            Self::Resolve => write!(f, "RESOLVE"),
            Self::Resume => write!(f, "RESUME"),
            Self::Suspend => write!(f, "SUSPEND"),
            Self::Unassign => write!(f, "UNASSIGN"),
            Self::Unknown => write!(f, "UNKNOWN"),
            Self::Update => write!(f, "UPDATE"),
        }
    }
}

impl Default for AuditLogOperationTypeEnum {
    fn default() -> AuditLogOperationTypeEnum {
        Self::Assign
    }
}
