/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuditLogEntityTypeEnum : The type of entity affected by the operation.
/// The type of entity affected by the operation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuditLogEntityTypeEnum {
    #[serde(rename = "AUTHORIZATION")]
    Authorization,
    #[serde(rename = "BATCH")]
    Batch,
    #[serde(rename = "DECISION")]
    Decision,
    #[serde(rename = "GROUP")]
    Group,
    #[serde(rename = "INCIDENT")]
    Incident,
    #[serde(rename = "JOB")]
    Job,
    #[serde(rename = "MAPPING_RULE")]
    MappingRule,
    #[serde(rename = "PROCESS_INSTANCE")]
    ProcessInstance,
    #[serde(rename = "RESOURCE")]
    Resource,
    #[serde(rename = "ROLE")]
    Role,
    #[serde(rename = "TENANT")]
    Tenant,
    #[serde(rename = "USER")]
    User,
    #[serde(rename = "USER_TASK")]
    UserTask,
    #[serde(rename = "VARIABLE")]
    Variable,
    #[serde(rename = "CLIENT")]
    Client,
}

impl std::fmt::Display for AuditLogEntityTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Authorization => write!(f, "AUTHORIZATION"),
            Self::Batch => write!(f, "BATCH"),
            Self::Decision => write!(f, "DECISION"),
            Self::Group => write!(f, "GROUP"),
            Self::Incident => write!(f, "INCIDENT"),
            Self::Job => write!(f, "JOB"),
            Self::MappingRule => write!(f, "MAPPING_RULE"),
            Self::ProcessInstance => write!(f, "PROCESS_INSTANCE"),
            Self::Resource => write!(f, "RESOURCE"),
            Self::Role => write!(f, "ROLE"),
            Self::Tenant => write!(f, "TENANT"),
            Self::User => write!(f, "USER"),
            Self::UserTask => write!(f, "USER_TASK"),
            Self::Variable => write!(f, "VARIABLE"),
            Self::Client => write!(f, "CLIENT"),
        }
    }
}

impl Default for AuditLogEntityTypeEnum {
    fn default() -> AuditLogEntityTypeEnum {
        Self::Authorization
    }
}
