/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuditLogCategoryEnum : The category of the audit log operation.
/// The category of the audit log operation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuditLogCategoryEnum {
    #[serde(rename = "ADMIN")]
    Admin,
    #[serde(rename = "DEPLOYED_RESOURCES")]
    DeployedResources,
    #[serde(rename = "USER_TASKS")]
    UserTasks,
}

impl std::fmt::Display for AuditLogCategoryEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Admin => write!(f, "ADMIN"),
            Self::DeployedResources => write!(f, "DEPLOYED_RESOURCES"),
            Self::UserTasks => write!(f, "USER_TASKS"),
        }
    }
}

impl Default for AuditLogCategoryEnum {
    fn default() -> AuditLogCategoryEnum {
        Self::Admin
    }
}
