/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthorizationFilter : Authorization search filter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthorizationFilter {
    /// The ID of the owner of permissions.
    #[serde(rename = "ownerId", skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<String>,
    #[serde(rename = "ownerType", skip_serializing_if = "Option::is_none")]
    pub owner_type: Option<models::OwnerTypeEnum>,
    /// The IDs of the resource to search permissions for.
    #[serde(rename = "resourceIds", skip_serializing_if = "Option::is_none")]
    pub resource_ids: Option<Vec<String>>,
    /// The names of the resource properties to search permissions for.
    #[serde(
        rename = "resourcePropertyNames",
        skip_serializing_if = "Option::is_none"
    )]
    pub resource_property_names: Option<Vec<String>>,
    /// The type of resource to search permissions for.
    #[serde(rename = "resourceType", skip_serializing_if = "Option::is_none")]
    pub resource_type: Option<models::ResourceTypeEnum>,
}

impl AuthorizationFilter {
    /// Authorization search filter.
    pub fn new() -> AuthorizationFilter {
        AuthorizationFilter {
            owner_id: None,
            owner_type: None,
            resource_ids: None,
            resource_property_names: None,
            resource_type: None,
        }
    }
}
