/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchOperationFilter : Batch operation filter request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchOperationFilter {
    /// The key (or operate legacy ID) of the batch operation.
    #[serde(rename = "batchOperationKey", skip_serializing_if = "Option::is_none")]
    pub batch_operation_key: Option<Box<models::BasicStringFilterProperty>>,
    /// The type of the batch operation.
    #[serde(rename = "operationType", skip_serializing_if = "Option::is_none")]
    pub operation_type: Option<Box<models::BatchOperationTypeFilterProperty>>,
    /// The state of the batch operation.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<Box<models::BatchOperationStateFilterProperty>>,
    /// The type of the actor who performed the operation.
    #[serde(rename = "actorType", skip_serializing_if = "Option::is_none")]
    pub actor_type: Option<models::AuditLogActorTypeEnum>,
    /// The ID of the actor who performed the operation.
    #[serde(rename = "actorId", skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<Box<models::StringFilterProperty>>,
}

impl BatchOperationFilter {
    /// Batch operation filter request.
    pub fn new() -> BatchOperationFilter {
        BatchOperationFilter {
            batch_operation_key: None,
            operation_type: None,
            state: None,
            actor_type: None,
            actor_id: None,
        }
    }
}
