/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchOperationItemResponse {
    #[serde(rename = "operationType")]
    pub operation_type: models::BatchOperationTypeEnum,
    /// The key (or operate legacy ID) of the batch operation.
    #[serde(rename = "batchOperationKey")]
    pub batch_operation_key: String,
    /// Key of the item, e.g. a process instance key.
    #[serde(rename = "itemKey")]
    pub item_key: String,
    /// The process instance key of the processed item. Null for batch-op types whose targets are not process instances (e.g. DELETE_DECISION_INSTANCE, DELETE_DECISION_DEFINITION, DELETE_PROCESS_DEFINITION).
    #[serde(
        rename = "processInstanceKey",
        deserialize_with = "Option::deserialize"
    )]
    pub process_instance_key: Option<Box<models::ProcessInstanceKey>>,
    /// The key of the root process instance. The root process instance is the top-level ancestor in the process instance hierarchy. This field is only present for data belonging to process instance hierarchies created in version 8.9 or later.
    #[serde(
        rename = "rootProcessInstanceKey",
        deserialize_with = "Option::deserialize"
    )]
    pub root_process_instance_key: Option<Box<models::ProcessInstanceKey>>,
    /// State of the item.
    #[serde(rename = "state")]
    pub state: State,
    /// The date this item was processed. This is `null` if the item has not yet been processed.
    #[serde(rename = "processedDate", deserialize_with = "Option::deserialize")]
    pub processed_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The error message from the engine in case of a failed operation.
    #[serde(rename = "errorMessage", deserialize_with = "Option::deserialize")]
    pub error_message: Option<String>,
}

impl BatchOperationItemResponse {
    pub fn new(
        operation_type: models::BatchOperationTypeEnum,
        batch_operation_key: String,
        item_key: String,
        process_instance_key: Option<models::ProcessInstanceKey>,
        root_process_instance_key: Option<models::ProcessInstanceKey>,
        state: State,
        processed_date: Option<chrono::DateTime<chrono::FixedOffset>>,
        error_message: Option<String>,
    ) -> BatchOperationItemResponse {
        BatchOperationItemResponse {
            operation_type,
            batch_operation_key,
            item_key,
            process_instance_key: if let Some(x) = process_instance_key {
                Some(Box::new(x))
            } else {
                None
            },
            root_process_instance_key: if let Some(x) = root_process_instance_key {
                Some(Box::new(x))
            } else {
                None
            },
            state,
            processed_date,
            error_message,
        }
    }
}
/// State of the item.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "SKIPPED")]
    Skipped,
    #[serde(rename = "CANCELED")]
    Canceled,
    #[serde(rename = "FAILED")]
    Failed,
}

impl Default for State {
    fn default() -> State {
        Self::Active
    }
}
