/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchOperationItemFilter : Batch operation item filter request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchOperationItemFilter {
    /// The key (or operate legacy ID) of the batch operation.
    #[serde(rename = "batchOperationKey", skip_serializing_if = "Option::is_none")]
    pub batch_operation_key: Option<Box<models::BasicStringFilterProperty>>,
    /// The key of the item, e.g. a process instance key.
    #[serde(rename = "itemKey", skip_serializing_if = "Option::is_none")]
    pub item_key: Option<Box<models::BasicStringFilterProperty>>,
    /// The process instance key of the processed item.
    #[serde(rename = "processInstanceKey", skip_serializing_if = "Option::is_none")]
    pub process_instance_key: Option<Box<models::ProcessInstanceKeyFilterProperty>>,
    /// The state of the batch operation.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<Box<models::BatchOperationItemStateFilterProperty>>,
    /// The type of the batch operation.
    #[serde(rename = "operationType", skip_serializing_if = "Option::is_none")]
    pub operation_type: Option<Box<models::BatchOperationTypeFilterProperty>>,
}

impl BatchOperationItemFilter {
    /// Batch operation item filter request.
    pub fn new() -> BatchOperationItemFilter {
        BatchOperationItemFilter {
            batch_operation_key: None,
            item_key: None,
            process_instance_key: None,
            state: None,
            operation_type: None,
        }
    }
}
