/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BrokerInfo : Provides information on a broker node.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrokerInfo {
    /// The unique (within a cluster) node ID for the broker.
    #[serde(rename = "nodeId")]
    pub node_id: i32,
    /// The hostname for reaching the broker.
    #[serde(rename = "host")]
    pub host: String,
    /// The port for reaching the broker.
    #[serde(rename = "port")]
    pub port: i32,
    /// A list of partitions managed or replicated on this broker.
    #[serde(rename = "partitions")]
    pub partitions: Vec<models::Partition>,
    /// The broker version.
    #[serde(rename = "version")]
    pub version: String,
}

impl BrokerInfo {
    /// Provides information on a broker node.
    pub fn new(
        node_id: i32,
        host: String,
        port: i32,
        partitions: Vec<models::Partition>,
        version: String,
    ) -> BrokerInfo {
        BrokerInfo {
            node_id,
            host,
            port,
            partitions,
            version,
        }
    }
}
