/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Changeset : JSON object with changed task attribute values.  The following attributes can be adjusted with this endpoint, additional attributes will be ignored:  * `candidateGroups` - reset by providing an empty list * `candidateUsers` - reset by providing an empty list * `dueDate` - reset by providing an empty String * `followUpDate` - reset by providing an empty String * `priority` - minimum 0, maximum 100, default 50  Providing any of those attributes with a `null` value or omitting it preserves the persisted attribute's value.  The assignee cannot be adjusted with this endpoint, use the Assign task endpoint. This ensures correct event emission for assignee changes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Changeset {
    /// The due date of the task. Reset by providing an empty String.
    #[serde(
        rename = "dueDate",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub due_date: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The follow-up date of the task. Reset by providing an empty String.
    #[serde(
        rename = "followUpDate",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub follow_up_date: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The list of candidate users of the task. Reset by providing an empty list.
    #[serde(
        rename = "candidateUsers",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub candidate_users: Option<Option<Vec<String>>>,
    /// The list of candidate groups of the task. Reset by providing an empty list.
    #[serde(
        rename = "candidateGroups",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub candidate_groups: Option<Option<Vec<String>>>,
    /// The priority of the task.
    #[serde(
        rename = "priority",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub priority: Option<Option<i32>>,
}

impl Changeset {
    /// JSON object with changed task attribute values.  The following attributes can be adjusted with this endpoint, additional attributes will be ignored:  * `candidateGroups` - reset by providing an empty list * `candidateUsers` - reset by providing an empty list * `dueDate` - reset by providing an empty String * `followUpDate` - reset by providing an empty String * `priority` - minimum 0, maximum 100, default 50  Providing any of those attributes with a `null` value or omitting it preserves the persisted attribute's value.  The assignee cannot be adjusted with this endpoint, use the Assign task endpoint. This ensures correct event emission for assignee changes.
    pub fn new() -> Changeset {
        Changeset {
            due_date: None,
            follow_up_date: None,
            candidate_users: None,
            candidate_groups: None,
            priority: None,
        }
    }
}
