/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CloudConfigurationResponse : Configuration for SaaS/cloud-specific settings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudConfigurationResponse {
    /// The cloud deployment stage.
    #[serde(rename = "stage", deserialize_with = "Option::deserialize")]
    pub stage: Option<models::CloudStage>,
}

impl CloudConfigurationResponse {
    /// Configuration for SaaS/cloud-specific settings.
    pub fn new(stage: Option<models::CloudStage>) -> CloudConfigurationResponse {
        CloudConfigurationResponse { stage }
    }
}
