/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClusterTakeHistoryBackupResponse : The snapshots scheduled on every targeted physical tenant. No cluster-level state is aggregated from the per-tenant outcomes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterTakeHistoryBackupResponse {
    /// The id requested for the backup on every targeted physical tenant.
    #[serde(rename = "backupId")]
    pub backup_id: i64,
    /// The outcome for each targeted physical tenant, ordered by physical tenant id.
    #[serde(rename = "physicalTenants")]
    pub physical_tenants: Vec<models::ClusterHistoryBackupTakeResult>,
}

impl ClusterTakeHistoryBackupResponse {
    /// The snapshots scheduled on every targeted physical tenant. No cluster-level state is aggregated from the per-tenant outcomes.
    pub fn new(
        backup_id: i64,
        physical_tenants: Vec<models::ClusterHistoryBackupTakeResult>,
    ) -> ClusterTakeHistoryBackupResponse {
        ClusterTakeHistoryBackupResponse {
            backup_id,
            physical_tenants,
        }
    }
}
