/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClusterRebalanceOperationPartition : One partition's plan, progress, and outcome within a rebalance.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterRebalanceOperationPartition {
    /// The unique ID of this partition, within its physical tenant.
    #[serde(rename = "partitionId")]
    pub partition_id: i32,
    /// The partition group this partition belongs to.
    #[serde(rename = "physicalTenantId")]
    pub physical_tenant_id: String,
    /// The leader last observed by this rebalance, or absent if there was no leader.
    #[serde(rename = "currentLeader", deserialize_with = "Option::deserialize")]
    pub current_leader: Option<String>,
    /// The leader selected when this rebalance was planned.
    #[serde(rename = "desiredLeader")]
    pub desired_leader: String,
    /// Where this rebalance has reached for the partition.
    #[serde(rename = "progress")]
    pub progress: Progress,
    /// The terminal outcome, present only when progress is COMPLETED.
    #[serde(rename = "result", deserialize_with = "Option::deserialize")]
    pub result: Option<Result>,
}

impl ClusterRebalanceOperationPartition {
    /// One partition's plan, progress, and outcome within a rebalance.
    pub fn new(
        partition_id: i32,
        physical_tenant_id: String,
        current_leader: Option<String>,
        desired_leader: String,
        progress: Progress,
        result: Option<Result>,
    ) -> ClusterRebalanceOperationPartition {
        ClusterRebalanceOperationPartition {
            partition_id,
            physical_tenant_id,
            current_leader,
            desired_leader,
            progress,
            result,
        }
    }
}
/// Where this rebalance has reached for the partition.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Progress {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "TRANSFERRING")]
    Transferring,
    #[serde(rename = "COMPLETED")]
    Completed,
}

impl Default for Progress {
    fn default() -> Progress {
        Self::Pending
    }
}
/// The terminal outcome, present only when progress is COMPLETED.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Result {
    #[serde(rename = "TRANSFERRED")]
    Transferred,
    #[serde(rename = "ALREADY_LEADER")]
    AlreadyLeader,
    #[serde(rename = "NOT_MEMBER")]
    NotMember,
    #[serde(rename = "NOT_REPLICATING")]
    NotReplicating,
    #[serde(rename = "UNREACHABLE")]
    Unreachable,
    #[serde(rename = "NOT_COORDINATOR")]
    NotCoordinator,
    #[serde(rename = "STALE_CONFIGURATION")]
    StaleConfiguration,
    #[serde(rename = "TRANSFER_IN_PROGRESS")]
    TransferInProgress,
    #[serde(rename = "LAG_TOO_HIGH")]
    LagTooHigh,
    #[serde(rename = "LEADER_INITIALIZING")]
    LeaderInitializing,
    #[serde(rename = "CONFIGURATION_CHANGE_IN_PROGRESS")]
    ConfigurationChangeInProgress,
    #[serde(rename = "PAUSE_FAILED")]
    PauseFailed,
    #[serde(rename = "REPLICATION_TIMED_OUT")]
    ReplicationTimedOut,
    #[serde(rename = "TIMEOUT_NOW_EXHAUSTED")]
    TimeoutNowExhausted,
    #[serde(rename = "LEADER_CHANGED")]
    LeaderChanged,
    #[serde(rename = "NO_LEADER")]
    NoLeader,
    #[serde(rename = "NO_RESPONSE")]
    NoResponse,
    #[serde(rename = "CANCELLED")]
    Cancelled,
}

impl Default for Result {
    fn default() -> Result {
        Self::Transferred
    }
}
