/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClusterModeChangeResponse : The planned changes resulting from a cluster mode transition request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterModeChangeResponse {
    /// The ID of the cluster change that was triggered by the request.
    #[serde(rename = "changeId")]
    pub change_id: String,
    /// The ordered list of operations that will be applied to complete the change.
    #[serde(rename = "plannedChanges")]
    pub planned_changes: Vec<models::ClusterModeChangeOperation>,
}

impl ClusterModeChangeResponse {
    /// The planned changes resulting from a cluster mode transition request.
    pub fn new(
        change_id: String,
        planned_changes: Vec<models::ClusterModeChangeOperation>,
    ) -> ClusterModeChangeResponse {
        ClusterModeChangeResponse {
            change_id,
            planned_changes,
        }
    }
}
