/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClusterBalanceResponse : The cluster's current per-partition balance state, the running rebalance, and the last completed rebalance.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterBalanceResponse {
    /// The cluster's aggregate balance state as of the time of the request.
    #[serde(rename = "state")]
    pub state: State,
    /// The balance state of each partition as of the time of the request.
    #[serde(rename = "partitions")]
    pub partitions: Vec<models::ClusterRebalancePartition>,
    /// Normally the rebalance currently running, or absent if no rebalance is running. For a dry-run response, this is instead the unexecuted plan of that dry run.
    #[serde(rename = "runningRebalance", deserialize_with = "Option::deserialize")]
    pub running_rebalance: Option<Box<models::ClusterRunningRebalance>>,
    /// The last completed non-dry-run rebalance this coordinator finished.
    #[serde(
        rename = "lastCompletedRebalance",
        deserialize_with = "Option::deserialize"
    )]
    pub last_completed_rebalance: Option<Box<models::ClusterCompletedRebalance>>,
}

impl ClusterBalanceResponse {
    /// The cluster's current per-partition balance state, the running rebalance, and the last completed rebalance.
    pub fn new(
        state: State,
        partitions: Vec<models::ClusterRebalancePartition>,
        running_rebalance: Option<models::ClusterRunningRebalance>,
        last_completed_rebalance: Option<models::ClusterCompletedRebalance>,
    ) -> ClusterBalanceResponse {
        ClusterBalanceResponse {
            state,
            partitions,
            running_rebalance: if let Some(x) = running_rebalance {
                Some(Box::new(x))
            } else {
                None
            },
            last_completed_rebalance: if let Some(x) = last_completed_rebalance {
                Some(Box::new(x))
            } else {
                None
            },
        }
    }
}
/// The cluster's aggregate balance state as of the time of the request.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "BALANCED")]
    Balanced,
    #[serde(rename = "BALANCING")]
    Balancing,
    #[serde(rename = "UNBALANCED")]
    Unbalanced,
}

impl Default for State {
    fn default() -> State {
        Self::Balanced
    }
}
