/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClusterRuntimeBackupTenantState : The checkpoint and backup state of one physical tenant.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterRuntimeBackupTenantState {
    /// The id of the physical tenant.
    #[serde(rename = "physicalTenantId")]
    pub physical_tenant_id: String,
    /// The checkpoint and backup state of this physical tenant's partitions.
    #[serde(rename = "state")]
    pub state: Box<models::RuntimeBackupState>,
}

impl ClusterRuntimeBackupTenantState {
    /// The checkpoint and backup state of one physical tenant.
    pub fn new(
        physical_tenant_id: String,
        state: models::RuntimeBackupState,
    ) -> ClusterRuntimeBackupTenantState {
        ClusterRuntimeBackupTenantState {
            physical_tenant_id,
            state: Box::new(state),
        }
    }
}
