/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClusterRuntimeBackupState : The checkpoint and backup state of each physical tenant. Nothing is aggregated across tenants: checkpoint ids and log positions only mean anything within one tenant's partitions.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterRuntimeBackupState {
    /// The runtime backup state of each targeted physical tenant, ordered by physical tenant id.
    #[serde(rename = "physicalTenants")]
    pub physical_tenants: Vec<models::ClusterRuntimeBackupTenantState>,
}

impl ClusterRuntimeBackupState {
    /// The checkpoint and backup state of each physical tenant. Nothing is aggregated across tenants: checkpoint ids and log positions only mean anything within one tenant's partitions.
    pub fn new(
        physical_tenants: Vec<models::ClusterRuntimeBackupTenantState>,
    ) -> ClusterRuntimeBackupState {
        ClusterRuntimeBackupState { physical_tenants }
    }
}
