/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClusterRestoreModeChangeOperation : The operation that transitions a broker to a mode once its partitions are restored.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterRestoreModeChangeOperation {
    /// The type of the operation.
    #[serde(rename = "operation")]
    pub operation: String,
    /// The ID of the broker that applies the operation, including its zone if it belongs to one.
    #[serde(rename = "brokerId")]
    pub broker_id: String,
    /// The mode the broker is transitioned to.
    #[serde(rename = "mode")]
    pub mode: String,
}

impl ClusterRestoreModeChangeOperation {
    /// The operation that transitions a broker to a mode once its partitions are restored.
    pub fn new(
        operation: String,
        broker_id: String,
        mode: String,
    ) -> ClusterRestoreModeChangeOperation {
        ClusterRestoreModeChangeOperation {
            operation,
            broker_id,
            mode,
        }
    }
}
