/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClusterRebalanceRequest : The settings to run a given rebalance with. Every setting is optional; an absent request body is equivalent to a body with every field absent, and means \"use the configured settings\".
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterRebalanceRequest {
    /// The highest replication lag (in bytes) that a desired leader may have for its transfer to be accepted.
    #[serde(
        rename = "replicationLagThreshold",
        skip_serializing_if = "Option::is_none"
    )]
    pub replication_lag_threshold: Option<i64>,
    /// How long a partition may stay frozen waiting for its desired leader to catch up (as a positive ISO-8601 duration).
    #[serde(rename = "replicationTimeout", skip_serializing_if = "Option::is_none")]
    pub replication_timeout: Option<String>,
    /// How many times a current leader may prompt the desired leader to take over leadership before giving up.
    #[serde(
        rename = "maxTransferAttempts",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_transfer_attempts: Option<i32>,
    /// How long the coordinator waits for a partition without a leader to acquire one before reporting `NO_LEADER` and moving on (as a positive ISO-8601 duration).
    #[serde(rename = "leaderWaitTimeout", skip_serializing_if = "Option::is_none")]
    pub leader_wait_timeout: Option<String>,
}

impl ClusterRebalanceRequest {
    /// The settings to run a given rebalance with. Every setting is optional; an absent request body is equivalent to a body with every field absent, and means \"use the configured settings\".
    pub fn new() -> ClusterRebalanceRequest {
        ClusterRebalanceRequest {
            replication_lag_threshold: None,
            replication_timeout: None,
            max_transfer_attempts: None,
            leader_wait_timeout: None,
        }
    }
}
