/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClusterBrokerInfo : Provides information on a broker node, independent of any physical tenant.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterBrokerInfo {
    /// The unique (within a cluster) broker identifier. When the cluster is not zoned, then it's a string that represents the nodeId (an integer). When the cluster is zoned, instead, it's of the form \"$zoneName_$nodeId\", providing uniqueness even across zones.
    #[serde(rename = "brokerId")]
    pub broker_id: String,
    /// The hostname for reaching the broker.
    #[serde(rename = "host")]
    pub host: String,
    /// The port for reaching the broker.
    #[serde(rename = "port")]
    pub port: i32,
    /// The broker version.
    #[serde(rename = "version")]
    pub version: String,
}

impl ClusterBrokerInfo {
    /// Provides information on a broker node, independent of any physical tenant.
    pub fn new(broker_id: String, host: String, port: i32, version: String) -> ClusterBrokerInfo {
        ClusterBrokerInfo {
            broker_id,
            host,
            port,
            version,
        }
    }
}
