/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConditionWaitStateDetails {
    /// The wait state type discriminator.
    #[serde(rename = "waitStateType")]
    pub wait_state_type: String,
    /// The condition expression that must evaluate to true to proceed.
    #[serde(rename = "expression")]
    pub expression: String,
    /// The variable events that trigger condition re-evaluation. Empty means all events.
    #[serde(rename = "events")]
    pub events: Vec<Events>,
}

impl ConditionWaitStateDetails {
    pub fn new(
        wait_state_type: String,
        expression: String,
        events: Vec<Events>,
    ) -> ConditionWaitStateDetails {
        ConditionWaitStateDetails {
            wait_state_type,
            expression,
            events,
        }
    }
}
/// The variable events that trigger condition re-evaluation. Empty means all events.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Events {
    #[serde(rename = "create")]
    Create,
    #[serde(rename = "update")]
    Update,
}

impl Default for Events {
    fn default() -> Events {
        Self::Create
    }
}
