/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DecisionDefinitionTypeEnum : The type of the decision. UNSPECIFIED is deprecated and should not be used anymore, for removal in 8.10
/// The type of the decision. UNSPECIFIED is deprecated and should not be used anymore, for removal in 8.10
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DecisionDefinitionTypeEnum {
    #[serde(rename = "DECISION_TABLE")]
    DecisionTable,
    #[serde(rename = "LITERAL_EXPRESSION")]
    LiteralExpression,
    #[serde(rename = "UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl std::fmt::Display for DecisionDefinitionTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DecisionTable => write!(f, "DECISION_TABLE"),
            Self::LiteralExpression => write!(f, "LITERAL_EXPRESSION"),
            Self::Unspecified => write!(f, "UNSPECIFIED"),
            Self::Unknown => write!(f, "UNKNOWN"),
        }
    }
}

impl Default for DecisionDefinitionTypeEnum {
    fn default() -> DecisionDefinitionTypeEnum {
        Self::DecisionTable
    }
}
