/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DecisionRequirementsFilter : Decision requirements search filter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecisionRequirementsFilter {
    /// The DMN name of the decision requirements.
    #[serde(
        rename = "decisionRequirementsName",
        skip_serializing_if = "Option::is_none"
    )]
    pub decision_requirements_name: Option<String>,
    /// the DMN ID of the decision requirements.
    #[serde(
        rename = "decisionRequirementsId",
        skip_serializing_if = "Option::is_none"
    )]
    pub decision_requirements_id: Option<String>,
    #[serde(
        rename = "decisionRequirementsKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub decision_requirements_key: Option<Box<models::DecisionRequirementsKey>>,
    /// The assigned version of the decision requirements.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
    /// The tenant ID of the decision requirements.
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<models::TenantId>,
    /// The name of the resource from which the decision requirements were parsed
    #[serde(rename = "resourceName", skip_serializing_if = "Option::is_none")]
    pub resource_name: Option<String>,
}

impl DecisionRequirementsFilter {
    /// Decision requirements search filter.
    pub fn new() -> DecisionRequirementsFilter {
        DecisionRequirementsFilter {
            decision_requirements_name: None,
            decision_requirements_id: None,
            decision_requirements_key: None,
            version: None,
            tenant_id: None,
            resource_name: None,
        }
    }
}
