/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecisionDefinitionSearchQuerySortRequest {
    /// The field to sort by.
    #[serde(rename = "field")]
    pub field: Field,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<models::SortOrderEnum>,
}

impl DecisionDefinitionSearchQuerySortRequest {
    pub fn new(field: Field) -> DecisionDefinitionSearchQuerySortRequest {
        DecisionDefinitionSearchQuerySortRequest { field, order: None }
    }
}
/// The field to sort by.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Field {
    #[serde(rename = "decisionDefinitionKey")]
    DecisionDefinitionKey,
    #[serde(rename = "decisionDefinitionId")]
    DecisionDefinitionId,
    #[serde(rename = "name")]
    Name,
    #[serde(rename = "version")]
    Version,
    #[serde(rename = "decisionRequirementsId")]
    DecisionRequirementsId,
    #[serde(rename = "decisionRequirementsKey")]
    DecisionRequirementsKey,
    #[serde(rename = "decisionRequirementsName")]
    DecisionRequirementsName,
    #[serde(rename = "decisionRequirementsVersion")]
    DecisionRequirementsVersion,
    #[serde(rename = "tenantId")]
    TenantId,
}

impl Default for Field {
    fn default() -> Field {
        Self::DecisionDefinitionKey
    }
}
