/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteResourceResponse {
    /// The system-assigned key for this resource, requested to be deleted.
    #[serde(rename = "resourceKey")]
    pub resource_key: Box<models::ResourceKey>,
    /// The batch operation created for asynchronously deleting the historic data.  Populated when `deleteHistory` is `true` and either the resource is a decision requirements definition, or the resource is a process definition that is already fully deleted from the runtime state (its history is purged directly by a batch operation).  For a process definition that still exists in the runtime state, deletion first drains the definition and its history is removed asynchronously as part of that lifecycle, so no batch operation is returned and this field is `null`. It is also `null` for forms and generic resources.
    #[serde(rename = "batchOperation", deserialize_with = "Option::deserialize")]
    pub batch_operation: Option<Box<models::BatchOperationCreatedResult>>,
}

impl DeleteResourceResponse {
    pub fn new(
        resource_key: models::ResourceKey,
        batch_operation: Option<models::BatchOperationCreatedResult>,
    ) -> DeleteResourceResponse {
        DeleteResourceResponse {
            resource_key: Box::new(resource_key),
            batch_operation: if let Some(x) = batch_operation {
                Some(Box::new(x))
            } else {
                None
            },
        }
    }
}
