/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentReference {
    /// Document discriminator. Always set to \"camunda\".
    #[serde(rename = "camunda.document.type")]
    pub camunda_document_type: CamundaDocumentType,
    /// The ID of the document store.
    #[serde(rename = "storeId")]
    pub store_id: String,
    /// The ID of the document.
    #[serde(rename = "documentId")]
    pub document_id: String,
    /// The hash of the document.
    #[serde(rename = "contentHash", deserialize_with = "Option::deserialize")]
    pub content_hash: Option<String>,
    #[serde(rename = "metadata")]
    pub metadata: Box<models::DocumentMetadataResponse>,
}

impl DocumentReference {
    pub fn new(
        camunda_document_type: CamundaDocumentType,
        store_id: String,
        document_id: String,
        content_hash: Option<String>,
        metadata: models::DocumentMetadataResponse,
    ) -> DocumentReference {
        DocumentReference {
            camunda_document_type,
            store_id,
            document_id,
            content_hash,
            metadata: Box::new(metadata),
        }
    }
}
/// Document discriminator. Always set to \"camunda\".
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CamundaDocumentType {
    #[serde(rename = "camunda")]
    Camunda,
}

impl Default for CamundaDocumentType {
    fn default() -> CamundaDocumentType {
        Self::Camunda
    }
}
