/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ElementInstanceFilterFields : Element instance filter fields.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ElementInstanceFilterFields {
    /// The process definition ID associated to this element instance.
    #[serde(
        rename = "processDefinitionId",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_id: Option<models::ProcessDefinitionId>,
    /// State of element instance as defined set of values.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<Box<models::ElementInstanceStateFilterProperty>>,
    /// Type of element as defined set of values.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    /// The element ID for this element instance.
    #[serde(rename = "elementId", skip_serializing_if = "Option::is_none")]
    pub element_id: Option<Box<models::ElementIdFilterProperty>>,
    /// The element name. This only works for data created with 8.8 and onwards. Instances from prior versions don't contain this data and cannot be found.
    #[serde(rename = "elementName", skip_serializing_if = "Option::is_none")]
    pub element_name: Option<Box<models::StringFilterProperty>>,
    /// Shows whether this element instance has an incident related to.
    #[serde(rename = "hasIncident", skip_serializing_if = "Option::is_none")]
    pub has_incident: Option<bool>,
    /// The unique identifier of the tenant.
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<models::TenantId>,
    /// The assigned key, which acts as a unique identifier for this element instance.
    #[serde(rename = "elementInstanceKey", skip_serializing_if = "Option::is_none")]
    pub element_instance_key: Option<Box<models::ElementInstanceKey>>,
    /// The process instance key associated to this element instance.
    #[serde(rename = "processInstanceKey", skip_serializing_if = "Option::is_none")]
    pub process_instance_key: Option<Box<models::ProcessInstanceKey>>,
    /// The process definition key associated to this element instance.
    #[serde(
        rename = "processDefinitionKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_key: Option<Box<models::ProcessDefinitionKey>>,
    /// The key of incident if field incident is true.
    #[serde(rename = "incidentKey", skip_serializing_if = "Option::is_none")]
    pub incident_key: Option<Box<models::IncidentKey>>,
    /// The start date of this element instance.
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<Box<models::DateTimeFilterProperty>>,
    /// The end date of this element instance.
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<Box<models::DateTimeFilterProperty>>,
    /// The scope key of this element instance. If provided with a process instance key it will return element instances that are immediate children of the process instance. If provided with an element instance key it will return element instances that are immediate children of the element instance.
    #[serde(
        rename = "elementInstanceScopeKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub element_instance_scope_key: Option<Box<String>>,
}

impl ElementInstanceFilterFields {
    /// Element instance filter fields.
    pub fn new() -> ElementInstanceFilterFields {
        ElementInstanceFilterFields {
            process_definition_id: None,
            state: None,
            r#type: None,
            element_id: None,
            element_name: None,
            has_incident: None,
            tenant_id: None,
            element_instance_key: None,
            process_instance_key: None,
            process_definition_key: None,
            incident_key: None,
            start_date: None,
            end_date: None,
            element_instance_scope_key: None,
        }
    }
}
/// Type of element as defined set of values.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "UNSPECIFIED")]
    Unspecified,
    #[serde(rename = "PROCESS")]
    Process,
    #[serde(rename = "SUB_PROCESS")]
    SubProcess,
    #[serde(rename = "EVENT_SUB_PROCESS")]
    EventSubProcess,
    #[serde(rename = "AD_HOC_SUB_PROCESS")]
    AdHocSubProcess,
    #[serde(rename = "AD_HOC_SUB_PROCESS_INNER_INSTANCE")]
    AdHocSubProcessInnerInstance,
    #[serde(rename = "START_EVENT")]
    StartEvent,
    #[serde(rename = "INTERMEDIATE_CATCH_EVENT")]
    IntermediateCatchEvent,
    #[serde(rename = "INTERMEDIATE_THROW_EVENT")]
    IntermediateThrowEvent,
    #[serde(rename = "BOUNDARY_EVENT")]
    BoundaryEvent,
    #[serde(rename = "END_EVENT")]
    EndEvent,
    #[serde(rename = "SERVICE_TASK")]
    ServiceTask,
    #[serde(rename = "RECEIVE_TASK")]
    ReceiveTask,
    #[serde(rename = "USER_TASK")]
    UserTask,
    #[serde(rename = "MANUAL_TASK")]
    ManualTask,
    #[serde(rename = "TASK")]
    Task,
    #[serde(rename = "EXCLUSIVE_GATEWAY")]
    ExclusiveGateway,
    #[serde(rename = "INCLUSIVE_GATEWAY")]
    InclusiveGateway,
    #[serde(rename = "PARALLEL_GATEWAY")]
    ParallelGateway,
    #[serde(rename = "EVENT_BASED_GATEWAY")]
    EventBasedGateway,
    #[serde(rename = "SEQUENCE_FLOW")]
    SequenceFlow,
    #[serde(rename = "MULTI_INSTANCE_BODY")]
    MultiInstanceBody,
    #[serde(rename = "CALL_ACTIVITY")]
    CallActivity,
    #[serde(rename = "BUSINESS_RULE_TASK")]
    BusinessRuleTask,
    #[serde(rename = "SCRIPT_TASK")]
    ScriptTask,
    #[serde(rename = "SEND_TASK")]
    SendTask,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl Default for Type {
    fn default() -> Type {
        Self::Unspecified
    }
}
