/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GlobalTaskListenerSearchQueryFilterRequest : Global listener filter request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalTaskListenerSearchQueryFilterRequest {
    /// Id of the global listener.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<Box<models::StringFilterProperty>>,
    /// Job type of the global listener.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Box<models::StringFilterProperty>>,
    /// Number of retries of the global listener.
    #[serde(rename = "retries", skip_serializing_if = "Option::is_none")]
    pub retries: Option<Box<models::IntegerFilterProperty>>,
    /// Event types of the global listener.
    #[serde(rename = "eventTypes", skip_serializing_if = "Option::is_none")]
    pub event_types: Option<Vec<models::GlobalTaskListenerEventTypeFilterProperty>>,
    /// Whether the listener runs after model-level listeners.
    #[serde(rename = "afterNonGlobal", skip_serializing_if = "Option::is_none")]
    pub after_non_global: Option<bool>,
    /// Priority of the global listener.
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Box<models::IntegerFilterProperty>>,
    /// How the global listener was defined.
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<models::GlobalListenerSourceFilterProperty>>,
}

impl GlobalTaskListenerSearchQueryFilterRequest {
    /// Global listener filter request.
    pub fn new() -> GlobalTaskListenerSearchQueryFilterRequest {
        GlobalTaskListenerSearchQueryFilterRequest {
            id: None,
            r#type: None,
            retries: None,
            event_types: None,
            after_non_global: None,
            priority: None,
            source: None,
        }
    }
}
