/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HistoryBackupStateCode : The aggregated state of a history backup, computed from the state of each of its snapshots.
/// The aggregated state of a history backup, computed from the state of each of its snapshots.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HistoryBackupStateCode {
    #[serde(rename = "IN_PROGRESS")]
    InProgress,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "INCOMPLETE")]
    Incomplete,
    #[serde(rename = "INCOMPATIBLE")]
    Incompatible,
}

impl std::fmt::Display for HistoryBackupStateCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InProgress => write!(f, "IN_PROGRESS"),
            Self::Completed => write!(f, "COMPLETED"),
            Self::Failed => write!(f, "FAILED"),
            Self::Incomplete => write!(f, "INCOMPLETE"),
            Self::Incompatible => write!(f, "INCOMPATIBLE"),
        }
    }
}

impl Default for HistoryBackupStateCode {
    fn default() -> HistoryBackupStateCode {
        Self::InProgress
    }
}
