/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HistoryBackupInfo : Detailed status of a history backup. The aggregated state is computed from the state of each of its snapshots as: - If every expected snapshot exists and all are complete, the overall state is   'COMPLETED'. - If one snapshot failed or is partial, the overall state is 'FAILED'. - Otherwise, if one snapshot is incompatible, the overall state is 'INCOMPATIBLE'. - Otherwise, if one snapshot is still running, the overall state is 'IN_PROGRESS'. - Otherwise, if snapshots are missing and the backup has not progressed within the   configured timeout, the overall state is 'INCOMPLETE'.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoryBackupInfo {
    /// The id of the backup.
    #[serde(rename = "backupId")]
    pub backup_id: i64,
    /// The aggregated state of the backup.
    #[serde(rename = "state")]
    pub state: models::HistoryBackupStateCode,
    /// Reason for failure if the state is 'FAILED'.
    #[serde(rename = "failureReason", deserialize_with = "Option::deserialize")]
    pub failure_reason: Option<String>,
    /// Detailed status of the backup per snapshot. Always lists every snapshot found for the backup; when the backup was read without snapshot detail, each entry carries only its name.
    #[serde(rename = "details")]
    pub details: Vec<models::HistoryBackupSnapshotInfo>,
}

impl HistoryBackupInfo {
    /// Detailed status of a history backup. The aggregated state is computed from the state of each of its snapshots as: - If every expected snapshot exists and all are complete, the overall state is   'COMPLETED'. - If one snapshot failed or is partial, the overall state is 'FAILED'. - Otherwise, if one snapshot is incompatible, the overall state is 'INCOMPATIBLE'. - Otherwise, if one snapshot is still running, the overall state is 'IN_PROGRESS'. - Otherwise, if snapshots are missing and the backup has not progressed within the   configured timeout, the overall state is 'INCOMPLETE'.
    pub fn new(
        backup_id: i64,
        state: models::HistoryBackupStateCode,
        failure_reason: Option<String>,
        details: Vec<models::HistoryBackupSnapshotInfo>,
    ) -> HistoryBackupInfo {
        HistoryBackupInfo {
            backup_id,
            state,
            failure_reason,
            details,
        }
    }
}
