/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IncidentStateEnum : Incident states with a defined set of values.
/// Incident states with a defined set of values.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IncidentStateEnum {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "MIGRATED")]
    Migrated,
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "RESOLVED")]
    Resolved,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl std::fmt::Display for IncidentStateEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Active => write!(f, "ACTIVE"),
            Self::Migrated => write!(f, "MIGRATED"),
            Self::Pending => write!(f, "PENDING"),
            Self::Resolved => write!(f, "RESOLVED"),
            Self::Unknown => write!(f, "UNKNOWN"),
        }
    }
}

impl Default for IncidentStateEnum {
    fn default() -> IncidentStateEnum {
        Self::Active
    }
}
