/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IncidentProcessInstanceStatisticsByDefinitionQuery {
    /// Filter criteria for the aggregated process instance statistics.
    #[serde(rename = "filter")]
    pub filter: Box<models::IncidentProcessInstanceStatisticsByDefinitionFilter>,
    /// Pagination parameters for the aggregated process instance statistics.
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<models::OffsetPagination>>,
    /// Sorting criteria for process instance statistics grouped by process definition.
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Vec<models::IncidentProcessInstanceStatisticsByDefinitionQuerySortRequest>>,
}

impl IncidentProcessInstanceStatisticsByDefinitionQuery {
    pub fn new(
        filter: models::IncidentProcessInstanceStatisticsByDefinitionFilter,
    ) -> IncidentProcessInstanceStatisticsByDefinitionQuery {
        IncidentProcessInstanceStatisticsByDefinitionQuery {
            filter: Box::new(filter),
            page: None,
            sort: None,
        }
    }
}
