/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InferredAncestorKeyInstruction : Instructs the engine to derive the ancestor scope key from the source element's hierarchy. The engine traverses the source element's ancestry to find an instance that matches one of the target element's flow scopes, ensuring the target is activated in the correct scope.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InferredAncestorKeyInstruction {
    /// The type of ancestor scope instruction.
    #[serde(rename = "ancestorScopeType")]
    pub ancestor_scope_type: String,
}

impl InferredAncestorKeyInstruction {
    /// Instructs the engine to derive the ancestor scope key from the source element's hierarchy. The engine traverses the source element's ancestry to find an instance that matches one of the target element's flow scopes, ensuring the target is activated in the correct scope.
    pub fn new(ancestor_scope_type: String) -> InferredAncestorKeyInstruction {
        InferredAncestorKeyInstruction {
            ancestor_scope_type,
        }
    }
}
