/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobErrorStatisticsFilter : Job error statistics search filter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobErrorStatisticsFilter {
    /// Start of the time window to filter metrics. ISO 8601 date-time format.
    #[serde(rename = "from")]
    pub from: chrono::DateTime<chrono::FixedOffset>,
    /// End of the time window to filter metrics. ISO 8601 date-time format.
    #[serde(rename = "to")]
    pub to: chrono::DateTime<chrono::FixedOffset>,
    /// Job type to return error metrics for.
    #[serde(rename = "jobType")]
    pub job_type: String,
    /// Optional error code filter with advanced search capabilities.
    #[serde(rename = "errorCode", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<Box<models::StringFilterProperty>>,
    /// Optional error message filter with advanced search capabilities.
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Box<models::StringFilterProperty>>,
}

impl JobErrorStatisticsFilter {
    /// Job error statistics search filter.
    pub fn new(
        from: chrono::DateTime<chrono::FixedOffset>,
        to: chrono::DateTime<chrono::FixedOffset>,
        job_type: String,
    ) -> JobErrorStatisticsFilter {
        JobErrorStatisticsFilter {
            from,
            to,
            job_type,
            error_code: None,
            error_message: None,
        }
    }
}
