/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobKindEnum : The job kind.
/// The job kind.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobKindEnum {
    #[serde(rename = "BPMN_ELEMENT")]
    BpmnElement,
    #[serde(rename = "EXECUTION_LISTENER")]
    ExecutionListener,
    #[serde(rename = "TASK_LISTENER")]
    TaskListener,
    #[serde(rename = "AD_HOC_SUB_PROCESS")]
    AdHocSubProcess,
}

impl std::fmt::Display for JobKindEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::BpmnElement => write!(f, "BPMN_ELEMENT"),
            Self::ExecutionListener => write!(f, "EXECUTION_LISTENER"),
            Self::TaskListener => write!(f, "TASK_LISTENER"),
            Self::AdHocSubProcess => write!(f, "AD_HOC_SUB_PROCESS"),
        }
    }
}

impl Default for JobKindEnum {
    fn default() -> JobKindEnum {
        Self::BpmnElement
    }
}
