/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobErrorStatisticsItem : Aggregated error metrics for a single error type and message combination.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobErrorStatisticsItem {
    /// The error code identifier.
    #[serde(rename = "errorCode")]
    pub error_code: String,
    /// The error message.
    #[serde(rename = "errorMessage")]
    pub error_message: String,
    /// Number of distinct workers that encountered this error.
    #[serde(rename = "workers")]
    pub workers: i32,
}

impl JobErrorStatisticsItem {
    /// Aggregated error metrics for a single error type and message combination.
    pub fn new(error_code: String, error_message: String, workers: i32) -> JobErrorStatisticsItem {
        JobErrorStatisticsItem {
            error_code,
            error_message,
            workers,
        }
    }
}
