/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobStateEnum : The state of the job.
/// The state of the job.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobStateEnum {
    #[serde(rename = "CANCELED")]
    Canceled,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "CREATED")]
    Created,
    #[serde(rename = "ERROR_THROWN")]
    ErrorThrown,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "MIGRATED")]
    Migrated,
    #[serde(rename = "RETRIES_UPDATED")]
    RetriesUpdated,
    #[serde(rename = "TIMED_OUT")]
    TimedOut,
}

impl std::fmt::Display for JobStateEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Canceled => write!(f, "CANCELED"),
            Self::Completed => write!(f, "COMPLETED"),
            Self::Created => write!(f, "CREATED"),
            Self::ErrorThrown => write!(f, "ERROR_THROWN"),
            Self::Failed => write!(f, "FAILED"),
            Self::Migrated => write!(f, "MIGRATED"),
            Self::RetriesUpdated => write!(f, "RETRIES_UPDATED"),
            Self::TimedOut => write!(f, "TIMED_OUT"),
        }
    }
}

impl Default for JobStateEnum {
    fn default() -> JobStateEnum {
        Self::Canceled
    }
}
