/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobActivationRequest {
    /// The job type, as defined in the BPMN process (e.g. <zeebe:taskDefinition type=\"payment-service\" />)
    #[serde(rename = "type")]
    pub r#type: String,
    /// The name of the worker activating the jobs, mostly used for logging purposes.
    #[serde(rename = "worker", skip_serializing_if = "Option::is_none")]
    pub worker: Option<String>,
    /// A job returned after this call will not be activated by another call until the timeout (in ms) has been reached.
    #[serde(rename = "timeout")]
    pub timeout: i64,
    /// The maximum jobs to activate by this request.
    #[serde(rename = "maxJobsToActivate")]
    pub max_jobs_to_activate: i32,
    /// A list of variables to fetch as the job variables; if empty, all visible variables at the time of activation for the scope of the job will be returned.
    #[serde(rename = "fetchVariable", skip_serializing_if = "Option::is_none")]
    pub fetch_variable: Option<Vec<String>>,
    /// The request will be completed when at least one job is activated or after the requestTimeout (in ms). If the requestTimeout = 0, a default timeout is used. If the requestTimeout < 0, long polling is disabled and the request is completed immediately, even when no job is activated.
    #[serde(rename = "requestTimeout", skip_serializing_if = "Option::is_none")]
    pub request_timeout: Option<i64>,
    /// A list of IDs of tenants for which to activate jobs.
    #[serde(rename = "tenantIds", skip_serializing_if = "Option::is_none")]
    pub tenant_ids: Option<Vec<models::TenantId>>,
    /// The tenant filtering strategy - determines whether to use provided tenant IDs or assigned tenant IDs from the authenticated principal's authorized tenants.
    #[serde(rename = "tenantFilter", skip_serializing_if = "Option::is_none")]
    pub tenant_filter: Option<models::TenantFilterEnum>,
    /// Whether to activate the jobs with a lease. When true, each activated job is assigned a distinct, opaque lease token, returned as ActivatedJobResult.leaseToken. The lease fences the complete, fail, and throw-error commands against a superseded activation of the same job (for example, after the job timed out or failed and was re-activated by another worker): a command carrying a stale lease token is rejected rather than racing with the newer activation. Once a job has been activated with a lease, it is served only to leasing workers of that job type; a homogeneous fleet per job type is recommended. Omit or set to false to activate jobs without a lease.
    #[serde(
        rename = "withLease",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub with_lease: Option<Option<bool>>,
}

impl JobActivationRequest {
    pub fn new(r#type: String, timeout: i64, max_jobs_to_activate: i32) -> JobActivationRequest {
        JobActivationRequest {
            r#type,
            worker: None,
            timeout,
            max_jobs_to_activate,
            fetch_variable: None,
            request_timeout: None,
            tenant_ids: None,
            tenant_filter: None,
            with_lease: None,
        }
    }
}
