/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LicenseResponse : The response of a license request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseResponse {
    /// True if the Camunda license is valid, false if otherwise
    #[serde(rename = "validLicense")]
    pub valid_license: bool,
    /// Will return the license type property of the Camunda license
    #[serde(rename = "licenseType")]
    pub license_type: String,
    /// Will be false when a license contains a non-commerical=true property
    #[serde(rename = "isCommercial")]
    pub is_commercial: bool,
    /// The date when the Camunda license expires
    #[serde(rename = "expiresAt", deserialize_with = "Option::deserialize")]
    pub expires_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl LicenseResponse {
    /// The response of a license request.
    pub fn new(
        valid_license: bool,
        license_type: String,
        is_commercial: bool,
        expires_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    ) -> LicenseResponse {
        LicenseResponse {
            valid_license,
            license_type,
            is_commercial,
            expires_at,
        }
    }
}
