/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MappingRuleFilter : Mapping rule search filter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MappingRuleFilter {
    /// The claim name to match against a token.
    #[serde(rename = "claimName", skip_serializing_if = "Option::is_none")]
    pub claim_name: Option<String>,
    /// The value of the claim to match.
    #[serde(rename = "claimValue", skip_serializing_if = "Option::is_none")]
    pub claim_value: Option<String>,
    /// The name of the mapping rule.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The ID of the mapping rule.
    #[serde(rename = "mappingRuleId", skip_serializing_if = "Option::is_none")]
    pub mapping_rule_id: Option<String>,
}

impl MappingRuleFilter {
    /// Mapping rule search filter.
    pub fn new() -> MappingRuleFilter {
        MappingRuleFilter {
            claim_name: None,
            claim_value: None,
            name: None,
            mapping_rule_id: None,
        }
    }
}
