/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageCorrelationRequest {
    /// The message name as defined in the BPMN process
    #[serde(rename = "name")]
    pub name: String,
    /// The correlation key of the message.
    #[serde(rename = "correlationKey", skip_serializing_if = "Option::is_none")]
    pub correlation_key: Option<String>,
    /// The message variables as JSON document
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// the tenant for which the message is published
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
}

impl MessageCorrelationRequest {
    pub fn new(name: String) -> MessageCorrelationRequest {
        MessageCorrelationRequest {
            name,
            correlation_key: None,
            variables: None,
            tenant_id: None,
        }
    }
}
