/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModifyProcessInstanceVariableInstruction : Instruction describing which variables to create or update.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModifyProcessInstanceVariableInstruction {
    /// JSON document that will instantiate the variables at the scope defined by the scopeId. It must be a JSON object, as variables will be mapped in a key-value fashion.
    #[serde(rename = "variables")]
    pub variables: std::collections::HashMap<String, serde_json::Value>,
    /// The id of the element in which scope the variables should be created. Leave empty to create the variables in the global scope of the process instance.
    #[serde(rename = "scopeId", skip_serializing_if = "Option::is_none")]
    pub scope_id: Option<String>,
}

impl ModifyProcessInstanceVariableInstruction {
    /// Instruction describing which variables to create or update.
    pub fn new(
        variables: std::collections::HashMap<String, serde_json::Value>,
    ) -> ModifyProcessInstanceVariableInstruction {
        ModifyProcessInstanceVariableInstruction {
            variables,
            scope_id: None,
        }
    }
}
