/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartitionBackupState : Detailed information about the backup state for a given partition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartitionBackupState {
    /// The id of the checkpoint this backup is based on.
    #[serde(rename = "checkpointId")]
    pub checkpoint_id: i64,
    /// The type of the backup.
    #[serde(rename = "checkpointType")]
    pub checkpoint_type: models::BackupType,
    /// The id of the partition. Omitted when nested inside a backup range's `start`/`end`, where the partition is already identified by the enclosing range.
    #[serde(rename = "partitionId", deserialize_with = "Option::deserialize")]
    pub partition_id: Option<i32>,
    /// The log position of the checkpoint this backup is based on.
    #[serde(rename = "checkpointPosition")]
    pub checkpoint_position: i64,
    /// The first log position included in this backup.
    #[serde(rename = "firstLogPosition")]
    pub first_log_position: i64,
    /// The timestamp at which the checkpoint was created.
    #[serde(rename = "checkpointTimestamp")]
    pub checkpoint_timestamp: chrono::DateTime<chrono::FixedOffset>,
}

impl PartitionBackupState {
    /// Detailed information about the backup state for a given partition.
    pub fn new(
        checkpoint_id: i64,
        checkpoint_type: models::BackupType,
        partition_id: Option<i32>,
        checkpoint_position: i64,
        first_log_position: i64,
        checkpoint_timestamp: chrono::DateTime<chrono::FixedOffset>,
    ) -> PartitionBackupState {
        PartitionBackupState {
            checkpoint_id,
            checkpoint_type,
            partition_id,
            checkpoint_position,
            first_log_position,
            checkpoint_timestamp,
        }
    }
}
