/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartitionCheckpointState : Detailed information about the checkpoint state for a given partition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartitionCheckpointState {
    /// The id of the checkpoint.
    #[serde(rename = "checkpointId")]
    pub checkpoint_id: i64,
    /// The type of the checkpoint.
    #[serde(rename = "checkpointType")]
    pub checkpoint_type: models::CheckpointType,
    /// The id of the partition.
    #[serde(rename = "partitionId")]
    pub partition_id: i32,
    /// The log position of the checkpoint.
    #[serde(rename = "checkpointPosition")]
    pub checkpoint_position: i64,
    /// The timestamp at which the checkpoint was created.
    #[serde(rename = "checkpointTimestamp")]
    pub checkpoint_timestamp: chrono::DateTime<chrono::FixedOffset>,
}

impl PartitionCheckpointState {
    /// Detailed information about the checkpoint state for a given partition.
    pub fn new(
        checkpoint_id: i64,
        checkpoint_type: models::CheckpointType,
        partition_id: i32,
        checkpoint_position: i64,
        checkpoint_timestamp: chrono::DateTime<chrono::FixedOffset>,
    ) -> PartitionCheckpointState {
        PartitionCheckpointState {
            checkpoint_id,
            checkpoint_type,
            partition_id,
            checkpoint_position,
            checkpoint_timestamp,
        }
    }
}
