/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PermissionTypeEnum : Specifies the type of permissions.
/// Specifies the type of permissions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PermissionTypeEnum {
    #[serde(rename = "ACCESS")]
    Access,
    #[serde(rename = "CANCEL_PROCESS_INSTANCE")]
    CancelProcessInstance,
    #[serde(rename = "CLAIM")]
    Claim,
    #[serde(rename = "CLAIM_USER_TASK")]
    ClaimUserTask,
    #[serde(rename = "COMPLETE")]
    Complete,
    #[serde(rename = "COMPLETE_USER_TASK")]
    CompleteUserTask,
    #[serde(rename = "CREATE")]
    Create,
    #[serde(rename = "CREATE_BATCH_OPERATION_CANCEL_PROCESS_INSTANCE")]
    CreateBatchOperationCancelProcessInstance,
    #[serde(rename = "CREATE_BATCH_OPERATION_DELETE_DECISION_DEFINITION")]
    CreateBatchOperationDeleteDecisionDefinition,
    #[serde(rename = "CREATE_BATCH_OPERATION_DELETE_DECISION_INSTANCE")]
    CreateBatchOperationDeleteDecisionInstance,
    #[serde(rename = "CREATE_BATCH_OPERATION_DELETE_PROCESS_DEFINITION")]
    CreateBatchOperationDeleteProcessDefinition,
    #[serde(rename = "CREATE_BATCH_OPERATION_DELETE_PROCESS_INSTANCE")]
    CreateBatchOperationDeleteProcessInstance,
    #[serde(rename = "CREATE_BATCH_OPERATION_MIGRATE_PROCESS_INSTANCE")]
    CreateBatchOperationMigrateProcessInstance,
    #[serde(rename = "CREATE_BATCH_OPERATION_MODIFY_PROCESS_INSTANCE")]
    CreateBatchOperationModifyProcessInstance,
    #[serde(rename = "CREATE_BATCH_OPERATION_RESOLVE_INCIDENT")]
    CreateBatchOperationResolveIncident,
    #[serde(rename = "CREATE_BATCH_OPERATION_SUSPEND_PROCESS_INSTANCE")]
    CreateBatchOperationSuspendProcessInstance,
    #[serde(rename = "CREATE_BATCH_OPERATION_UPDATE_JOB")]
    CreateBatchOperationUpdateJob,
    #[serde(rename = "CREATE_DECISION_INSTANCE")]
    CreateDecisionInstance,
    #[serde(rename = "CREATE_PROCESS_INSTANCE")]
    CreateProcessInstance,
    #[serde(rename = "CREATE_TASK_LISTENER")]
    CreateTaskListener,
    #[serde(rename = "DELETE")]
    Delete,
    #[serde(rename = "DELETE_DECISION_INSTANCE")]
    DeleteDecisionInstance,
    #[serde(rename = "DELETE_DRD")]
    DeleteDrd,
    #[serde(rename = "DELETE_FORM")]
    DeleteForm,
    #[serde(rename = "DELETE_PROCESS")]
    DeleteProcess,
    #[serde(rename = "DELETE_PROCESS_INSTANCE")]
    DeleteProcessInstance,
    #[serde(rename = "DELETE_RESOURCE")]
    DeleteResource,
    #[serde(rename = "DELETE_TASK_LISTENER")]
    DeleteTaskListener,
    #[serde(rename = "EVALUATE")]
    Evaluate,
    #[serde(rename = "MODIFY_PROCESS_INSTANCE")]
    ModifyProcessInstance,
    #[serde(rename = "PAUSE")]
    Pause,
    #[serde(rename = "READ")]
    Read,
    #[serde(rename = "READ_DECISION_DEFINITION")]
    ReadDecisionDefinition,
    #[serde(rename = "READ_DECISION_INSTANCE")]
    ReadDecisionInstance,
    #[serde(rename = "READ_JOB_METRIC")]
    ReadJobMetric,
    #[serde(rename = "READ_PROCESS_DEFINITION")]
    ReadProcessDefinition,
    #[serde(rename = "READ_PROCESS_INSTANCE")]
    ReadProcessInstance,
    #[serde(rename = "READ_USAGE_METRIC")]
    ReadUsageMetric,
    #[serde(rename = "READ_USER_TASK")]
    ReadUserTask,
    #[serde(rename = "READ_TASK_LISTENER")]
    ReadTaskListener,
    #[serde(rename = "RESTORE")]
    Restore,
    #[serde(rename = "REVEAL")]
    Reveal,
    #[serde(rename = "SUSPEND_PROCESS_INSTANCE")]
    SuspendProcessInstance,
    #[serde(rename = "UPDATE")]
    Update,
    #[serde(rename = "UPDATE_PROCESS_INSTANCE")]
    UpdateProcessInstance,
    #[serde(rename = "UPDATE_USER_TASK")]
    UpdateUserTask,
    #[serde(rename = "UPDATE_TASK_LISTENER")]
    UpdateTaskListener,
}

impl std::fmt::Display for PermissionTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Access => write!(f, "ACCESS"),
            Self::CancelProcessInstance => write!(f, "CANCEL_PROCESS_INSTANCE"),
            Self::Claim => write!(f, "CLAIM"),
            Self::ClaimUserTask => write!(f, "CLAIM_USER_TASK"),
            Self::Complete => write!(f, "COMPLETE"),
            Self::CompleteUserTask => write!(f, "COMPLETE_USER_TASK"),
            Self::Create => write!(f, "CREATE"),
            Self::CreateBatchOperationCancelProcessInstance => {
                write!(f, "CREATE_BATCH_OPERATION_CANCEL_PROCESS_INSTANCE")
            }
            Self::CreateBatchOperationDeleteDecisionDefinition => {
                write!(f, "CREATE_BATCH_OPERATION_DELETE_DECISION_DEFINITION")
            }
            Self::CreateBatchOperationDeleteDecisionInstance => {
                write!(f, "CREATE_BATCH_OPERATION_DELETE_DECISION_INSTANCE")
            }
            Self::CreateBatchOperationDeleteProcessDefinition => {
                write!(f, "CREATE_BATCH_OPERATION_DELETE_PROCESS_DEFINITION")
            }
            Self::CreateBatchOperationDeleteProcessInstance => {
                write!(f, "CREATE_BATCH_OPERATION_DELETE_PROCESS_INSTANCE")
            }
            Self::CreateBatchOperationMigrateProcessInstance => {
                write!(f, "CREATE_BATCH_OPERATION_MIGRATE_PROCESS_INSTANCE")
            }
            Self::CreateBatchOperationModifyProcessInstance => {
                write!(f, "CREATE_BATCH_OPERATION_MODIFY_PROCESS_INSTANCE")
            }
            Self::CreateBatchOperationResolveIncident => {
                write!(f, "CREATE_BATCH_OPERATION_RESOLVE_INCIDENT")
            }
            Self::CreateBatchOperationSuspendProcessInstance => {
                write!(f, "CREATE_BATCH_OPERATION_SUSPEND_PROCESS_INSTANCE")
            }
            Self::CreateBatchOperationUpdateJob => write!(f, "CREATE_BATCH_OPERATION_UPDATE_JOB"),
            Self::CreateDecisionInstance => write!(f, "CREATE_DECISION_INSTANCE"),
            Self::CreateProcessInstance => write!(f, "CREATE_PROCESS_INSTANCE"),
            Self::CreateTaskListener => write!(f, "CREATE_TASK_LISTENER"),
            Self::Delete => write!(f, "DELETE"),
            Self::DeleteDecisionInstance => write!(f, "DELETE_DECISION_INSTANCE"),
            Self::DeleteDrd => write!(f, "DELETE_DRD"),
            Self::DeleteForm => write!(f, "DELETE_FORM"),
            Self::DeleteProcess => write!(f, "DELETE_PROCESS"),
            Self::DeleteProcessInstance => write!(f, "DELETE_PROCESS_INSTANCE"),
            Self::DeleteResource => write!(f, "DELETE_RESOURCE"),
            Self::DeleteTaskListener => write!(f, "DELETE_TASK_LISTENER"),
            Self::Evaluate => write!(f, "EVALUATE"),
            Self::ModifyProcessInstance => write!(f, "MODIFY_PROCESS_INSTANCE"),
            Self::Pause => write!(f, "PAUSE"),
            Self::Read => write!(f, "READ"),
            Self::ReadDecisionDefinition => write!(f, "READ_DECISION_DEFINITION"),
            Self::ReadDecisionInstance => write!(f, "READ_DECISION_INSTANCE"),
            Self::ReadJobMetric => write!(f, "READ_JOB_METRIC"),
            Self::ReadProcessDefinition => write!(f, "READ_PROCESS_DEFINITION"),
            Self::ReadProcessInstance => write!(f, "READ_PROCESS_INSTANCE"),
            Self::ReadUsageMetric => write!(f, "READ_USAGE_METRIC"),
            Self::ReadUserTask => write!(f, "READ_USER_TASK"),
            Self::ReadTaskListener => write!(f, "READ_TASK_LISTENER"),
            Self::Restore => write!(f, "RESTORE"),
            Self::Reveal => write!(f, "REVEAL"),
            Self::SuspendProcessInstance => write!(f, "SUSPEND_PROCESS_INSTANCE"),
            Self::Update => write!(f, "UPDATE"),
            Self::UpdateProcessInstance => write!(f, "UPDATE_PROCESS_INSTANCE"),
            Self::UpdateUserTask => write!(f, "UPDATE_USER_TASK"),
            Self::UpdateTaskListener => write!(f, "UPDATE_TASK_LISTENER"),
        }
    }
}

impl Default for PermissionTypeEnum {
    fn default() -> PermissionTypeEnum {
        Self::Access
    }
}
