/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PhysicalTenantBrokerTopology : The partitions of one physical tenant that one broker manages or replicates.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PhysicalTenantBrokerTopology {
    /// The unique (within a cluster) identifier of the broker, as reported in the cluster-level broker list.
    #[serde(rename = "brokerId")]
    pub broker_id: String,
    /// The partitions of this physical tenant managed or replicated on this broker.
    #[serde(rename = "partitions")]
    pub partitions: Vec<models::Partition>,
}

impl PhysicalTenantBrokerTopology {
    /// The partitions of one physical tenant that one broker manages or replicates.
    pub fn new(
        broker_id: String,
        partitions: Vec<models::Partition>,
    ) -> PhysicalTenantBrokerTopology {
        PhysicalTenantBrokerTopology {
            broker_id,
            partitions,
        }
    }
}
