/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProblemDetail : A Problem detail object as described in [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457). There may be additional properties specific to the problem type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProblemDetail {
    /// A URI identifying the problem type.
    #[serde(rename = "type")]
    pub r#type: String,
    /// A summary of the problem type.
    #[serde(rename = "title")]
    pub title: String,
    /// The HTTP status code for this problem.
    #[serde(rename = "status")]
    pub status: i32,
    /// An explanation of the problem in more detail.
    #[serde(rename = "detail")]
    pub detail: String,
    /// A URI path identifying the origin of the problem.
    #[serde(rename = "instance")]
    pub instance: String,
}

impl ProblemDetail {
    /// A Problem detail object as described in [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457). There may be additional properties specific to the problem type.
    pub fn new(
        r#type: String,
        title: String,
        status: i32,
        detail: String,
        instance: String,
    ) -> ProblemDetail {
        ProblemDetail {
            r#type,
            title,
            status,
            detail,
            instance,
        }
    }
}
