/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessInstanceSearchQuerySortRequest {
    /// The field to sort by.
    #[serde(rename = "field")]
    pub field: Field,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<models::SortOrderEnum>,
}

impl ProcessInstanceSearchQuerySortRequest {
    pub fn new(field: Field) -> ProcessInstanceSearchQuerySortRequest {
        ProcessInstanceSearchQuerySortRequest { field, order: None }
    }
}
/// The field to sort by.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Field {
    #[serde(rename = "processInstanceKey")]
    ProcessInstanceKey,
    #[serde(rename = "processDefinitionId")]
    ProcessDefinitionId,
    #[serde(rename = "processDefinitionName")]
    ProcessDefinitionName,
    #[serde(rename = "processDefinitionVersion")]
    ProcessDefinitionVersion,
    #[serde(rename = "processDefinitionVersionTag")]
    ProcessDefinitionVersionTag,
    #[serde(rename = "processDefinitionKey")]
    ProcessDefinitionKey,
    #[serde(rename = "parentProcessInstanceKey")]
    ParentProcessInstanceKey,
    #[serde(rename = "parentElementInstanceKey")]
    ParentElementInstanceKey,
    #[serde(rename = "startDate")]
    StartDate,
    #[serde(rename = "endDate")]
    EndDate,
    #[serde(rename = "suspendedDate")]
    SuspendedDate,
    #[serde(rename = "state")]
    State,
    #[serde(rename = "hasIncident")]
    HasIncident,
    #[serde(rename = "tenantId")]
    TenantId,
    #[serde(rename = "businessId")]
    BusinessId,
}

impl Default for Field {
    fn default() -> Field {
        Self::ProcessInstanceKey
    }
}
