/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProcessInstanceModificationActivateInstruction : Instruction describing an element to activate.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessInstanceModificationActivateInstruction {
    /// The id of the element to activate.
    #[serde(rename = "elementId")]
    pub element_id: models::ElementId,
    /// Instructions describing which variables to create or update.
    #[serde(
        rename = "variableInstructions",
        skip_serializing_if = "Option::is_none"
    )]
    pub variable_instructions: Option<Vec<models::ModifyProcessInstanceVariableInstruction>>,
    /// The key of the ancestor scope the element instance should be created in. Set to -1 to create the new element instance within an existing element instance of the flow scope. If multiple instances of the target element's flow scope exist, choose one specifically with this property by providing its key.
    #[serde(
        rename = "ancestorElementInstanceKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub ancestor_element_instance_key: Option<Box<models::ElementInstanceKey>>,
}

impl ProcessInstanceModificationActivateInstruction {
    /// Instruction describing an element to activate.
    pub fn new(element_id: models::ElementId) -> ProcessInstanceModificationActivateInstruction {
        ProcessInstanceModificationActivateInstruction {
            element_id,
            variable_instructions: None,
            ancestor_element_instance_key: None,
        }
    }
}
