/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProcessInstanceModificationMoveInstruction : Instruction describing a move operation. This instruction will terminate active element instances based on the sourceElementInstruction and activate a new element instance for each terminated one at targetElementId. Note that, for multi-instance activities, only the multi-instance body instances will activate new element instances at the target id.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessInstanceModificationMoveInstruction {
    #[serde(rename = "sourceElementInstruction")]
    pub source_element_instruction: Box<models::SourceElementInstruction>,
    /// The target element id.
    #[serde(rename = "targetElementId")]
    pub target_element_id: models::ElementId,
    #[serde(
        rename = "ancestorScopeInstruction",
        skip_serializing_if = "Option::is_none"
    )]
    pub ancestor_scope_instruction: Option<Box<models::AncestorScopeInstruction>>,
    /// Instructions describing which variables to create or update.
    #[serde(
        rename = "variableInstructions",
        skip_serializing_if = "Option::is_none"
    )]
    pub variable_instructions: Option<Vec<models::ModifyProcessInstanceVariableInstruction>>,
}

impl ProcessInstanceModificationMoveInstruction {
    /// Instruction describing a move operation. This instruction will terminate active element instances based on the sourceElementInstruction and activate a new element instance for each terminated one at targetElementId. Note that, for multi-instance activities, only the multi-instance body instances will activate new element instances at the target id.
    pub fn new(
        source_element_instruction: models::SourceElementInstruction,
        target_element_id: models::ElementId,
    ) -> ProcessInstanceModificationMoveInstruction {
        ProcessInstanceModificationMoveInstruction {
            source_element_instruction: Box::new(source_element_instruction),
            target_element_id,
            ancestor_scope_instruction: None,
            variable_instructions: None,
        }
    }
}
