/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProcessDefinitionFilter : Process definition search filter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessDefinitionFilter {
    /// Name of this process definition.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Box<models::StringFilterProperty>>,
    /// Whether to only return the latest version of each process definition. When using this filter, pagination functionality is limited, you can only paginate forward using `after` and `limit`. The response contains no `startCursor` in the `page`, and requests ignore the `from` and `before` in the `page`. When using this filter, sorting is limited to `processDefinitionId` and `tenantId` fields only.
    #[serde(rename = "isLatestVersion", skip_serializing_if = "Option::is_none")]
    pub is_latest_version: Option<bool>,
    /// Resource name of this process definition.
    #[serde(rename = "resourceName", skip_serializing_if = "Option::is_none")]
    pub resource_name: Option<String>,
    /// Version of this process definition.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
    /// Version tag of this process definition.
    #[serde(rename = "versionTag", skip_serializing_if = "Option::is_none")]
    pub version_tag: Option<String>,
    /// Process definition ID of this process definition.
    #[serde(
        rename = "processDefinitionId",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_id: Option<Box<models::StringFilterProperty>>,
    /// Tenant ID of this process definition.
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    /// The key for this process definition.
    #[serde(
        rename = "processDefinitionKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_key: Option<Box<models::ProcessDefinitionKey>>,
    /// Indicates whether the start event of the process has an associated Form Key.
    #[serde(rename = "hasStartForm", skip_serializing_if = "Option::is_none")]
    pub has_start_form: Option<bool>,
}

impl ProcessDefinitionFilter {
    /// Process definition search filter.
    pub fn new() -> ProcessDefinitionFilter {
        ProcessDefinitionFilter {
            name: None,
            is_latest_version: None,
            resource_name: None,
            version: None,
            version_tag: None,
            process_definition_id: None,
            tenant_id: None,
            process_definition_key: None,
            has_start_form: None,
        }
    }
}
