/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProcessInstanceModificationMoveBatchOperationInstruction : Instructions describing a move operation. This instruction will terminate all active element instances at `sourceElementId` and activate a new element instance for each terminated one at `targetElementId`. The new element instances are created in the parent scope of the source element instances.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessInstanceModificationMoveBatchOperationInstruction {
    /// The source element ID.
    #[serde(rename = "sourceElementId")]
    pub source_element_id: String,
    /// The target element ID.
    #[serde(rename = "targetElementId")]
    pub target_element_id: String,
}

impl ProcessInstanceModificationMoveBatchOperationInstruction {
    /// Instructions describing a move operation. This instruction will terminate all active element instances at `sourceElementId` and activate a new element instance for each terminated one at `targetElementId`. The new element instances are created in the parent scope of the source element instances.
    pub fn new(
        source_element_id: String,
        target_element_id: String,
    ) -> ProcessInstanceModificationMoveBatchOperationInstruction {
        ProcessInstanceModificationMoveBatchOperationInstruction {
            source_element_id,
            target_element_id,
        }
    }
}
