/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessInstanceFilterFields {
    /// The start date.
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<Box<models::DateTimeFilterProperty>>,
    /// The end date.
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<Box<models::DateTimeFilterProperty>>,
    /// The process instance state.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<Box<models::ProcessInstanceStateFilterProperty>>,
    /// Whether this process instance has a related incident or not.
    #[serde(rename = "hasIncident", skip_serializing_if = "Option::is_none")]
    pub has_incident: Option<bool>,
    /// The tenant id.
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Box<models::StringFilterProperty>>,
    /// The process instance variables.
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<Vec<models::VariableValueFilterProperty>>,
    /// The key of this process instance.
    #[serde(rename = "processInstanceKey", skip_serializing_if = "Option::is_none")]
    pub process_instance_key: Option<Box<models::ProcessInstanceKeyFilterProperty>>,
    /// The parent process instance key.
    #[serde(
        rename = "parentProcessInstanceKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent_process_instance_key: Option<Box<models::ProcessInstanceKeyFilterProperty>>,
    /// The parent element instance key.
    #[serde(
        rename = "parentElementInstanceKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent_element_instance_key: Option<Box<models::ElementInstanceKeyFilterProperty>>,
    /// The batch operation id. **Deprecated**: Use `batchOperationKey` instead. This field will be removed in a future release. If both `batchOperationId` and `batchOperationKey` are provided, the request will be rejected with a 400 error.
    #[serde(rename = "batchOperationId", skip_serializing_if = "Option::is_none")]
    pub batch_operation_id: Option<Box<models::StringFilterProperty>>,
    /// The batch operation key.
    #[serde(rename = "batchOperationKey", skip_serializing_if = "Option::is_none")]
    pub batch_operation_key: Option<Box<models::StringFilterProperty>>,
    /// The error message related to the process.
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Box<models::StringFilterProperty>>,
    /// Whether the process has failed jobs with retries left.
    #[serde(rename = "hasRetriesLeft", skip_serializing_if = "Option::is_none")]
    pub has_retries_left: Option<bool>,
    /// The state of the element instances associated with the process instance.
    #[serde(
        rename = "elementInstanceState",
        skip_serializing_if = "Option::is_none"
    )]
    pub element_instance_state: Option<Box<models::ElementInstanceStateFilterProperty>>,
    /// The element id associated with the process instance.
    #[serde(rename = "elementId", skip_serializing_if = "Option::is_none")]
    pub element_id: Option<Box<models::StringFilterProperty>>,
    /// Whether the element instance has an incident or not.
    #[serde(
        rename = "hasElementInstanceIncident",
        skip_serializing_if = "Option::is_none"
    )]
    pub has_element_instance_incident: Option<bool>,
    /// The incident error hash code, associated with this process.
    #[serde(
        rename = "incidentErrorHashCode",
        skip_serializing_if = "Option::is_none"
    )]
    pub incident_error_hash_code: Option<Box<models::IntegerFilterProperty>>,
    /// List of tags. Tags need to start with a letter; then alphanumerics, `_`, `-`, `:`, or `.`; length ≤ 100.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// The business id associated with the process instance.
    #[serde(rename = "businessId", skip_serializing_if = "Option::is_none")]
    pub business_id: Option<Box<models::StringFilterProperty>>,
    /// The process definition id.
    #[serde(
        rename = "processDefinitionId",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_id: Option<Box<models::StringFilterProperty>>,
    /// The process definition name.
    #[serde(
        rename = "processDefinitionName",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_name: Option<Box<models::StringFilterProperty>>,
    /// The process definition version.
    #[serde(
        rename = "processDefinitionVersion",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_version: Option<Box<models::IntegerFilterProperty>>,
    /// The process definition version tag.
    #[serde(
        rename = "processDefinitionVersionTag",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_version_tag: Option<Box<models::StringFilterProperty>>,
    /// The process definition key.
    #[serde(
        rename = "processDefinitionKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_key: Option<Box<models::ProcessDefinitionKeyFilterProperty>>,
}

impl ProcessInstanceFilterFields {
    pub fn new() -> ProcessInstanceFilterFields {
        ProcessInstanceFilterFields {
            start_date: None,
            end_date: None,
            state: None,
            has_incident: None,
            tenant_id: None,
            variables: None,
            process_instance_key: None,
            parent_process_instance_key: None,
            parent_element_instance_key: None,
            batch_operation_id: None,
            batch_operation_key: None,
            error_message: None,
            has_retries_left: None,
            element_instance_state: None,
            element_id: None,
            has_element_instance_incident: None,
            incident_error_hash_code: None,
            tags: None,
            business_id: None,
            process_definition_id: None,
            process_definition_name: None,
            process_definition_version: None,
            process_definition_version_tag: None,
            process_definition_key: None,
        }
    }
}
