/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProcessInstanceMigrationBatchOperationPlan : The migration instructions describe how to migrate a process instance from one process definition to another.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessInstanceMigrationBatchOperationPlan {
    /// The target process definition key.
    #[serde(rename = "targetProcessDefinitionKey")]
    pub target_process_definition_key: Box<models::ProcessDefinitionKey>,
    /// The mapping instructions.
    #[serde(rename = "mappingInstructions")]
    pub mapping_instructions: Vec<models::MigrateProcessInstanceMappingInstruction>,
}

impl ProcessInstanceMigrationBatchOperationPlan {
    /// The migration instructions describe how to migrate a process instance from one process definition to another.
    pub fn new(
        target_process_definition_key: models::ProcessDefinitionKey,
        mapping_instructions: Vec<models::MigrateProcessInstanceMappingInstruction>,
    ) -> ProcessInstanceMigrationBatchOperationPlan {
        ProcessInstanceMigrationBatchOperationPlan {
            target_process_definition_key: Box::new(target_process_definition_key),
            mapping_instructions,
        }
    }
}
