/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ResourceTypeEnum : The type of resource to add/remove permissions to/from.
/// The type of resource to add/remove permissions to/from.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResourceTypeEnum {
    #[serde(rename = "AUDIT_LOG")]
    AuditLog,
    #[serde(rename = "AUTHORIZATION")]
    Authorization,
    #[serde(rename = "BACKUP")]
    Backup,
    #[serde(rename = "BATCH")]
    Batch,
    #[serde(rename = "CLUSTER_VARIABLE")]
    ClusterVariable,
    #[serde(rename = "COMPONENT")]
    Component,
    #[serde(rename = "DECISION_DEFINITION")]
    DecisionDefinition,
    #[serde(rename = "DECISION_REQUIREMENTS_DEFINITION")]
    DecisionRequirementsDefinition,
    #[serde(rename = "DOCUMENT")]
    Document,
    #[serde(rename = "EXPORTER")]
    Exporter,
    #[serde(rename = "EXPRESSION")]
    Expression,
    #[serde(rename = "GLOBAL_LISTENER")]
    GlobalListener,
    #[serde(rename = "GROUP")]
    Group,
    #[serde(rename = "MAPPING_RULE")]
    MappingRule,
    #[serde(rename = "MESSAGE")]
    Message,
    #[serde(rename = "PROCESS_DEFINITION")]
    ProcessDefinition,
    #[serde(rename = "RESOURCE")]
    Resource,
    #[serde(rename = "ROLE")]
    Role,
    #[serde(rename = "SECRET")]
    Secret,
    #[serde(rename = "SYSTEM")]
    System,
    #[serde(rename = "TENANT")]
    Tenant,
    #[serde(rename = "USER")]
    User,
    #[serde(rename = "USER_TASK")]
    UserTask,
}

impl std::fmt::Display for ResourceTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AuditLog => write!(f, "AUDIT_LOG"),
            Self::Authorization => write!(f, "AUTHORIZATION"),
            Self::Backup => write!(f, "BACKUP"),
            Self::Batch => write!(f, "BATCH"),
            Self::ClusterVariable => write!(f, "CLUSTER_VARIABLE"),
            Self::Component => write!(f, "COMPONENT"),
            Self::DecisionDefinition => write!(f, "DECISION_DEFINITION"),
            Self::DecisionRequirementsDefinition => write!(f, "DECISION_REQUIREMENTS_DEFINITION"),
            Self::Document => write!(f, "DOCUMENT"),
            Self::Exporter => write!(f, "EXPORTER"),
            Self::Expression => write!(f, "EXPRESSION"),
            Self::GlobalListener => write!(f, "GLOBAL_LISTENER"),
            Self::Group => write!(f, "GROUP"),
            Self::MappingRule => write!(f, "MAPPING_RULE"),
            Self::Message => write!(f, "MESSAGE"),
            Self::ProcessDefinition => write!(f, "PROCESS_DEFINITION"),
            Self::Resource => write!(f, "RESOURCE"),
            Self::Role => write!(f, "ROLE"),
            Self::Secret => write!(f, "SECRET"),
            Self::System => write!(f, "SYSTEM"),
            Self::Tenant => write!(f, "TENANT"),
            Self::User => write!(f, "USER"),
            Self::UserTask => write!(f, "USER_TASK"),
        }
    }
}

impl Default for ResourceTypeEnum {
    fn default() -> ResourceTypeEnum {
        Self::AuditLog
    }
}
