/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchQueryPageResponse : Pagination information about the search results.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchQueryPageResponse {
    /// Total items matching the criteria.
    #[serde(rename = "totalItems")]
    pub total_items: i64,
    /// Indicates whether the `totalItems` value has been capped due to system limits. When true, `totalItems` is a lower bound and the actual number of matching items is greater than the reported value.
    #[serde(rename = "hasMoreTotalItems")]
    pub has_more_total_items: bool,
    /// The cursor value for getting the previous page of results. Use this in the `before` field of an ensuing request.
    #[serde(rename = "startCursor", deserialize_with = "Option::deserialize")]
    pub start_cursor: Option<String>,
    /// The cursor value for getting the next page of results. Use this in the `after` field of an ensuing request.
    #[serde(rename = "endCursor", deserialize_with = "Option::deserialize")]
    pub end_cursor: Option<String>,
}

impl SearchQueryPageResponse {
    /// Pagination information about the search results.
    pub fn new(
        total_items: i64,
        has_more_total_items: bool,
        start_cursor: Option<String>,
        end_cursor: Option<String>,
    ) -> SearchQueryPageResponse {
        SearchQueryPageResponse {
            total_items,
            has_more_total_items,
            start_cursor,
            end_cursor,
        }
    }
}
