/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignalWaitStateDetails {
    /// The wait state type discriminator.
    #[serde(rename = "waitStateType")]
    pub wait_state_type: String,
    /// The name of the signal being awaited.
    #[serde(rename = "signalName")]
    pub signal_name: String,
}

impl SignalWaitStateDetails {
    pub fn new(wait_state_type: String, signal_name: String) -> SignalWaitStateDetails {
        SignalWaitStateDetails {
            wait_state_type,
            signal_name,
        }
    }
}
