/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SourceElementIdInstruction : Defines an instruction with a sourceElementId. The move instruction with this sourceType will terminate all active element instances with the sourceElementId and activate a new element instance for each terminated one at targetElementId.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourceElementIdInstruction {
    /// The type of source element instruction.
    #[serde(rename = "sourceType")]
    pub source_type: String,
    /// The id of the source element for the move instruction.
    #[serde(rename = "sourceElementId")]
    pub source_element_id: String,
}

impl SourceElementIdInstruction {
    /// Defines an instruction with a sourceElementId. The move instruction with this sourceType will terminate all active element instances with the sourceElementId and activate a new element instance for each terminated one at targetElementId.
    pub fn new(source_type: String, source_element_id: String) -> SourceElementIdInstruction {
        SourceElementIdInstruction {
            source_type,
            source_element_id,
        }
    }
}
