/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TopologyResponse : The response of a topology request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopologyResponse {
    /// A list of brokers that are part of this cluster.
    #[serde(rename = "brokers")]
    pub brokers: Vec<models::BrokerInfo>,
    /// The cluster Id.
    #[serde(rename = "clusterId", deserialize_with = "Option::deserialize")]
    pub cluster_id: Option<String>,
    /// The number of brokers in the cluster.
    #[serde(rename = "clusterSize")]
    pub cluster_size: i32,
    /// The number of partitions are spread across the cluster.
    #[serde(rename = "partitionsCount")]
    pub partitions_count: i32,
    /// The configured replication factor for this cluster.
    #[serde(rename = "replicationFactor")]
    pub replication_factor: i32,
    /// The version of the Zeebe Gateway.
    #[serde(rename = "gatewayVersion")]
    pub gateway_version: String,
    /// ID of the last completed change
    #[serde(rename = "lastCompletedChangeId")]
    pub last_completed_change_id: String,
}

impl TopologyResponse {
    /// The response of a topology request.
    pub fn new(
        brokers: Vec<models::BrokerInfo>,
        cluster_id: Option<String>,
        cluster_size: i32,
        partitions_count: i32,
        replication_factor: i32,
        gateway_version: String,
        last_completed_change_id: String,
    ) -> TopologyResponse {
        TopologyResponse {
            brokers,
            cluster_id,
            cluster_size,
            partitions_count,
            replication_factor,
            gateway_version,
            last_completed_change_id,
        }
    }
}
