/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGlobalTaskListenerRequest {
    /// The name of the job type, used as a reference to specify which job workers request the respective listener job.
    #[serde(rename = "type")]
    pub r#type: String,
    /// Number of retries for the listener job.
    #[serde(rename = "retries", skip_serializing_if = "Option::is_none")]
    pub retries: Option<i32>,
    /// Whether the listener should run after model-level listeners.
    #[serde(rename = "afterNonGlobal", skip_serializing_if = "Option::is_none")]
    pub after_non_global: Option<bool>,
    /// The priority of the listener. Higher priority listeners are executed before lower priority ones.
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    /// List of user task event types that trigger the listener.
    #[serde(rename = "eventTypes")]
    pub event_types: Vec<models::GlobalTaskListenerEventTypeEnum>,
}

impl UpdateGlobalTaskListenerRequest {
    pub fn new(
        r#type: String,
        event_types: Vec<models::GlobalTaskListenerEventTypeEnum>,
    ) -> UpdateGlobalTaskListenerRequest {
        UpdateGlobalTaskListenerRequest {
            r#type,
            retries: None,
            after_non_global: None,
            priority: None,
            event_types,
        }
    }
}
