/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageMetricsResponseItem {
    /// The amount of created root process instances.
    #[serde(rename = "processInstances")]
    pub process_instances: i64,
    /// The amount of executed decision instances.
    #[serde(rename = "decisionInstances")]
    pub decision_instances: i64,
    /// The amount of unique active task users.
    #[serde(rename = "assignees")]
    pub assignees: i64,
}

impl UsageMetricsResponseItem {
    pub fn new(
        process_instances: i64,
        decision_instances: i64,
        assignees: i64,
    ) -> UsageMetricsResponseItem {
        UsageMetricsResponseItem {
            process_instances,
            decision_instances,
            assignees,
        }
    }
}
