/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserTaskAuditLogFilter : The user task audit log search filters.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserTaskAuditLogFilter {
    /// The audit log operation type search filter.
    #[serde(rename = "operationType", skip_serializing_if = "Option::is_none")]
    pub operation_type: Option<Box<models::OperationTypeFilterProperty>>,
    /// The audit log result search filter.
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::AuditLogResultFilterProperty>>,
    /// The audit log timestamp filter.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Box<models::DateTimeFilterProperty>>,
    /// The actor type search filter.
    #[serde(rename = "actorType", skip_serializing_if = "Option::is_none")]
    pub actor_type: Option<Box<models::AuditLogActorTypeFilterProperty>>,
    /// The actor ID search filter.
    #[serde(rename = "actorId", skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<Box<models::StringFilterProperty>>,
}

impl UserTaskAuditLogFilter {
    /// The user task audit log search filters.
    pub fn new() -> UserTaskAuditLogFilter {
        UserTaskAuditLogFilter {
            operation_type: None,
            result: None,
            timestamp: None,
            actor_type: None,
            actor_id: None,
        }
    }
}
