/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserTaskFilter : User task filter request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserTaskFilter {
    /// The user task state.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<Box<models::UserTaskStateFilterProperty>>,
    /// The assignee of the user task.
    #[serde(rename = "assignee", skip_serializing_if = "Option::is_none")]
    pub assignee: Option<Box<models::StringFilterProperty>>,
    /// The business ID of the owning process instance the user task belongs to. This only works for user tasks created with 8.10 and onwards. Tasks from prior versions don't contain this data and cannot be found.
    #[serde(rename = "businessId", skip_serializing_if = "Option::is_none")]
    pub business_id: Option<Box<models::StringFilterProperty>>,
    /// The priority of the user task.
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Box<models::IntegerFilterProperty>>,
    /// The element ID of the user task.
    #[serde(rename = "elementId", skip_serializing_if = "Option::is_none")]
    pub element_id: Option<models::ElementId>,
    /// The task name. This only works for data created with 8.8 and onwards. Instances from prior versions don't contain this data and cannot be found.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Box<models::StringFilterProperty>>,
    /// The candidate group for this user task.
    #[serde(rename = "candidateGroup", skip_serializing_if = "Option::is_none")]
    pub candidate_group: Option<Box<models::StringFilterProperty>>,
    /// The candidate user for this user task.
    #[serde(rename = "candidateUser", skip_serializing_if = "Option::is_none")]
    pub candidate_user: Option<Box<models::StringFilterProperty>>,
    /// Tenant ID of this user task.
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Box<models::StringFilterProperty>>,
    /// The ID of the process definition.
    #[serde(
        rename = "processDefinitionId",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_id: Option<Box<models::ProcessDefinitionIdFilterProperty>>,
    /// The user task creation date.
    #[serde(rename = "creationDate", skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<Box<models::DateTimeFilterProperty>>,
    /// The user task completion date.
    #[serde(rename = "completionDate", skip_serializing_if = "Option::is_none")]
    pub completion_date: Option<Box<models::DateTimeFilterProperty>>,
    /// The user task follow-up date.
    #[serde(rename = "followUpDate", skip_serializing_if = "Option::is_none")]
    pub follow_up_date: Option<Box<models::DateTimeFilterProperty>>,
    /// The user task due date.
    #[serde(rename = "dueDate", skip_serializing_if = "Option::is_none")]
    pub due_date: Option<Box<models::DateTimeFilterProperty>>,
    /// The variables of the process instance.
    #[serde(
        rename = "processInstanceVariables",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_instance_variables: Option<Vec<models::VariableValueFilterProperty>>,
    /// The local variables of the user task.
    #[serde(rename = "localVariables", skip_serializing_if = "Option::is_none")]
    pub local_variables: Option<Vec<models::VariableValueFilterProperty>>,
    /// The key for this user task.
    #[serde(rename = "userTaskKey", skip_serializing_if = "Option::is_none")]
    pub user_task_key: Option<Box<models::UserTaskKey>>,
    /// The key of the process definition.
    #[serde(
        rename = "processDefinitionKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_definition_key: Option<Box<models::ProcessDefinitionKeyFilterProperty>>,
    /// The key of the process instance.
    #[serde(rename = "processInstanceKey", skip_serializing_if = "Option::is_none")]
    pub process_instance_key: Option<Box<models::ProcessInstanceKeyFilterProperty>>,
    /// The key of the element instance.
    #[serde(rename = "elementInstanceKey", skip_serializing_if = "Option::is_none")]
    pub element_instance_key: Option<Box<models::ElementInstanceKey>>,
    /// List of tags. Tags need to start with a letter; then alphanumerics, `_`, `-`, `:`, or `.`; length ≤ 100.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl UserTaskFilter {
    /// User task filter request.
    pub fn new() -> UserTaskFilter {
        UserTaskFilter {
            state: None,
            assignee: None,
            business_id: None,
            priority: None,
            element_id: None,
            name: None,
            candidate_group: None,
            candidate_user: None,
            tenant_id: None,
            process_definition_id: None,
            creation_date: None,
            completion_date: None,
            follow_up_date: None,
            due_date: None,
            process_instance_variables: None,
            local_variables: None,
            user_task_key: None,
            process_definition_key: None,
            process_instance_key: None,
            element_instance_key: None,
            tags: None,
        }
    }
}
