/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserTaskStateEnum : The state of the user task. Note: FAILED state is only for legacy job-worker-based tasks.
/// The state of the user task. Note: FAILED state is only for legacy job-worker-based tasks.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserTaskStateEnum {
    #[serde(rename = "CREATING")]
    Creating,
    #[serde(rename = "CREATED")]
    Created,
    #[serde(rename = "ASSIGNING")]
    Assigning,
    #[serde(rename = "UPDATING")]
    Updating,
    #[serde(rename = "COMPLETING")]
    Completing,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "CANCELING")]
    Canceling,
    #[serde(rename = "CANCELED")]
    Canceled,
    #[serde(rename = "FAILED")]
    Failed,
}

impl std::fmt::Display for UserTaskStateEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Creating => write!(f, "CREATING"),
            Self::Created => write!(f, "CREATED"),
            Self::Assigning => write!(f, "ASSIGNING"),
            Self::Updating => write!(f, "UPDATING"),
            Self::Completing => write!(f, "COMPLETING"),
            Self::Completed => write!(f, "COMPLETED"),
            Self::Canceling => write!(f, "CANCELING"),
            Self::Canceled => write!(f, "CANCELED"),
            Self::Failed => write!(f, "FAILED"),
        }
    }
}

impl Default for UserTaskStateEnum {
    fn default() -> UserTaskStateEnum {
        Self::Creating
    }
}
