/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserTaskCompletionRequest {
    /// The variables to complete the user task with.
    #[serde(
        rename = "variables",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub variables: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// A custom action value that will be accessible from user task events resulting from this endpoint invocation. If not provided, it will default to \"complete\".
    #[serde(
        rename = "action",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub action: Option<Option<String>>,
}

impl UserTaskCompletionRequest {
    pub fn new() -> UserTaskCompletionRequest {
        UserTaskCompletionRequest {
            variables: None,
            action: None,
        }
    }
}
