/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserTaskEffectiveVariableSearchQueryRequest : User task effective variable search query request. Uses offset-based pagination only.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserTaskEffectiveVariableSearchQueryRequest {
    /// Pagination parameters.
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<models::OffsetPagination>>,
    /// Sort field criteria.
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Vec<models::UserTaskVariableSearchQuerySortRequest>>,
    /// The user task variable search filters.
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::UserTaskVariableFilter>>,
}

impl UserTaskEffectiveVariableSearchQueryRequest {
    /// User task effective variable search query request. Uses offset-based pagination only.
    pub fn new() -> UserTaskEffectiveVariableSearchQueryRequest {
        UserTaskEffectiveVariableSearchQueryRequest {
            page: None,
            sort: None,
            filter: None,
        }
    }
}
