/*
 * Orchestration Cluster API
 *
 * API for communicating with a Camunda 8 cluster.  ## Conventions  ### Enum value casing  Server-side, enum-typed request fields accept any casing of a documented value (for example `ACTIVE`, `active`, and `Active` are all accepted on input). Responses always use the canonical casing shown in this specification.  This permissive request behavior is a server-side convenience and is **not** part of the OpenAPI enum contract — SDKs generated from this specification by strict generators may reject non-canonical casing on the client side. For portability across SDKs, always send the canonical casing shown in this document.
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WaitStateDetails : Wait-state-specific details of an element instance.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "waitStateType")]
pub enum WaitStateDetails {
    #[serde(rename = "JOB")]
    Job(Box<models::JobWaitStateDetails>),
    #[serde(rename = "MESSAGE")]
    Message(Box<models::MessageWaitStateDetails>),
    #[serde(rename = "USER_TASK")]
    UserTask(Box<models::UserTaskWaitStateDetails>),
    #[serde(rename = "TIMER")]
    Timer(Box<models::TimerWaitStateDetails>),
    #[serde(rename = "SIGNAL")]
    Signal(Box<models::SignalWaitStateDetails>),
    #[serde(rename = "CONDITION")]
    Condition(Box<models::ConditionWaitStateDetails>),
}

impl Default for WaitStateDetails {
    fn default() -> Self {
        Self::Job(Default::default())
    }
}

/// The variable events that trigger condition re-evaluation. Empty means all events.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Events {
    #[serde(rename = "create")]
    Create,
    #[serde(rename = "update")]
    Update,
}

impl Default for Events {
    fn default() -> Events {
        Self::Create
    }
}
