"""Hook 13 — dependent-presence couplings declared with ``x-present-when``.

OpenAPI 3.x cannot say that a response field is present only when the request set a
particular flag, so the specification states it out of band: a field-level
``x-present-when: {request: <flag>, equals: true}`` marker on the conditional field
(upstream camunda/camunda#62777, applied to ``ActivatedJobResult.jobLeaseToken``).

Rust has no dependent typing over a runtime-configured flag, so the guarantee has to
live in the hand-written runtime. This hook emits the couplings as data
(``present_when_generated.rs``) so that runtime enforces what the specification declares
rather than a relationship hardcoded from memory: if upstream renames the flag, moves
the field, or adds a second conditional field, the generated table changes and the
guards in ``present_when.rs`` fail.

Deliberately generic over the number of markers. A second ``x-present-when`` field is
carried into the table automatically, and the enforcement guard — not this hook — is
what reports that the runtime has not absorbed it yet.
"""

from __future__ import annotations

from .common import Context

NUMBER = 13
NAME = "present-when"

HEADER = """\
// @generated by scripts/postprocess.py (hook 13) — DO NOT EDIT.
//
// Dependent-presence couplings the specification declares with `x-present-when`:
// `RESPONSE_SCHEMA.RESPONSE_FIELD` is present exactly when a request set `REQUEST_FLAG`.
// OpenAPI cannot express this, so the runtime carries it and `present_when.rs` is the
// evidence it still matches the specification.

/// A dependent-presence relationship declared by `x-present-when`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct PresentWhenCoupling {
    /// The schema carrying the conditional field.
    pub response_schema: &'static str,
    /// The field that is present only under the flag.
    pub response_field: &'static str,
    /// The request flag whose truth makes the field present.
    pub request_flag: &'static str,
}
"""


def _rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def derive_couplings(schemas: dict) -> list[tuple[str, str, str]]:
    """Extract every ``x-present-when`` coupling from the schemas as ``(schema, field, flag)``.

    Raises ``SystemExit`` on a malformed marker or an empty result, so a spec that meant to
    declare a coupling cannot silently produce an empty table.
    """
    couplings = []
    for schema_name in sorted(schemas):
        schema = schemas[schema_name]
        if not isinstance(schema, dict):
            continue
        for field_name in sorted((schema.get("properties") or {})):
            field = schema["properties"][field_name]
            if not isinstance(field, dict):
                continue
            # Key presence, not truthiness: an explicit `x-present-when: null` is a
            # malformed marker, and `.get()` would let it masquerade as an absent one
            # and be skipped, so the runtime would drift from a spec that meant to
            # declare a coupling. Let it reach the validation below and fail loudly.
            if "x-present-when" not in field:
                continue
            marker = field["x-present-when"]
            request = marker.get("request") if isinstance(marker, dict) else None
            # `request` must be a non-empty string, not merely truthy: a numeric or object
            # `request` would otherwise reach the renderer and crash with an opaque
            # AttributeError instead of this explicit diagnostic.
            if not isinstance(marker, dict) or not isinstance(request, str) or not request or marker.get("equals") is not True:
                raise SystemExit(
                    f"hook 13: x-present-when on {schema_name}.{field_name} is {marker!r}, which is "
                    "not the 'present when <flag> is true' shape the runtime guards are built on. "
                    "Teach this hook the new shape rather than dropping the marker."
                )
            couplings.append((schema_name, field_name, request))

    if not couplings:
        raise SystemExit(
            "hook 13: the bundled spec declares no x-present-when markers. Either the "
            "bundler is stripping the vendor key or upstream removed it; emitting an empty "
            "table would silently retire the runtime guards built on it."
        )
    return couplings


def render(couplings: list[tuple[str, str, str]]) -> str:
    """Render the derived couplings as the generated Rust source."""
    lines = [HEADER, "\n"]
    lines.append("/// Every dependent-presence coupling the specification declares, ordered by\n")
    lines.append("/// schema then field so the table is stable across regenerations.\n")
    lines.append("pub(crate) const PRESENT_WHEN_COUPLINGS: &[PresentWhenCoupling] = &[\n")
    for schema_name, field_name, flag in couplings:
        lines.append("    PresentWhenCoupling {\n")
        lines.append(f"        response_schema: {_rust_str(schema_name)},\n")
        lines.append(f"        response_field: {_rust_str(field_name)},\n")
        lines.append(f"        request_flag: {_rust_str(flag)},\n")
        lines.append("    },\n")
    lines.append("];\n")
    return "".join(lines)


def run(ctx: Context) -> None:
    couplings = derive_couplings(ctx.schemas)
    sdk_root = ctx.client_dir.parent
    out_path = sdk_root / "src" / "runtime" / "present_when_generated.rs"
    out_path.write_text(render(couplings), encoding="utf-8")
    ctx.log(NAME, f"wrote {out_path.relative_to(sdk_root)}: {len(couplings)} coupling(s)")
